// ═══════════════════════════════════════════════════════
// data.js — Eureka! Chemistry Database
// ═══════════════════════════════════════════════════════

const STARTER_ATOMS = ['H','O','C','N'];

const ATOM_UNLOCKS = {
  // Wave 1: from starters (H,O,C,N)
  H2O: ['S'], CO2: ['Na'], NH3: ['Cl'],
  // Wave 2: from S,Na,Cl
  NaCl: ['Fe'], ATMOSPHERE: ['Ca'], H2S: ['P'],
  // Wave 3: from Fe,Ca,P
  STEEL: ['Mg'], BONES: ['K'], FeS: ['F'],
  // Wave 4: from Mg,K,F
  MgO: ['Al'], CEMENT: ['Si'], FERTILIZER: ['Cu'], BAKING_SODA: ['Zn'],
  // Wave 5: from Al,Si,Cu,Zn
  BRASS: ['Sn'], HF: ['He'], NEUTRALIZATION: ['Li'], CuSO4: ['Br'], H3PO4: ['I'],
  // Wave 6: from Sn,He,Li,Br,I
  BRONZE: ['Ti'], Al2O3: ['Cr'], ZnO: ['Mn'], LiOH: ['Ni'], Br2: ['Ne','Ar'],
  // Wave 7: from Ti,Cr,Mn,Ni,Ne,Ar
  STAINLESS: ['Co'], TiO2: ['Ag'], MnO2: ['Pb'], NEON_SIGN: ['Ba'], NaBr: ['W'],
  // Wave 8: from Co,Ag,Pb,Ba,W
  MIRROR: ['Au'], LI_BATTERY: ['Pt'], SOLDER: ['Hg'], LIGHT_BULB: ['U'],
};

const E = {
  // ── STARTER ATOMS (first 4 always available) ──
  H:  { id:'H',  name:'Hydrogen',   symbol:'H',  sub:'',  emoji:'⚛️', tier:'atom', color:'#FF6B9D', shadow:'rgba(255,107,157,0.5)', tc:'white',
        fact:'The most abundant element in the universe. Stars are basically giant balls of hydrogen trying to explode. Mostly succeeding.' },
  O:  { id:'O',  name:'Oxygen',     symbol:'O',  sub:'',  emoji:'💨', tier:'atom', color:'#FF4444', shadow:'rgba(255,68,68,0.5)', tc:'white',
        fact:'Makes up 21% of our atmosphere. Without it you have about 4 minutes. Appreciate it.' },
  C:  { id:'C',  name:'Carbon',     symbol:'C',  sub:'',  emoji:'⬛', tier:'atom', color:'#666677', shadow:'rgba(100,100,120,0.5)', tc:'white',
        fact:'The backbone of ALL life on Earth. Also makes up diamonds, pencils, and coal. Very versatile atom. Shows up everywhere.' },
  N:  { id:'N',  name:'Nitrogen',   symbol:'N',  sub:'',  emoji:'💙', tier:'atom', color:'#4477EE', shadow:'rgba(68,119,238,0.5)', tc:'white',
        fact:'78% of the air you breathe is nitrogen. You are literally swimming in it right now. You just can\'t use it without help.' },

  // ── UNLOCKABLE ATOMS ──
  Na: { id:'Na', name:'Sodium',     symbol:'Na', sub:'',  emoji:'✨', tier:'atom', color:'#FFD23F', shadow:'rgba(255,210,63,0.5)', tc:'#333', unlockedBy:'CO2',
        fact:'A soft metal that EXPLODES when it touches water. Yes, explodes. And yet you eat it every day in salt. Chemistry is wild.' },
  Cl: { id:'Cl', name:'Chlorine',   symbol:'Cl', sub:'',  emoji:'💚', tier:'atom', color:'#00CC88', shadow:'rgba(0,204,136,0.5)', tc:'#002', unlockedBy:'NH3',
        fact:'A toxic, yellow-green gas used as a chemical weapon in WWI. Combined with sodium it makes table salt. Perspective is everything.' },
  S:  { id:'S',  name:'Sulfur',     symbol:'S',  sub:'',  emoji:'💛', tier:'atom', color:'#FFAA00', shadow:'rgba(255,170,0,0.5)', tc:'#332', unlockedBy:'H2O',
        fact:'Smells like rotten eggs. Found around volcanoes. Used in gunpowder. Makes your hair curly. Busy atom.' },
  Fe: { id:'Fe', name:'Iron',       symbol:'Fe', sub:'',  emoji:'⚙️', tier:'atom', color:'#BB6633', shadow:'rgba(187,102,51,0.5)', tc:'white', unlockedBy:'NaCl',
        fact:'Makes your blood red by carrying oxygen around your body. Also makes up most of Earth\'s core. It\'s doing a lot.' },
  Ca: { id:'Ca', name:'Calcium',    symbol:'Ca', sub:'',  emoji:'🦴', tier:'atom', color:'#CCCCCC', shadow:'rgba(180,180,180,0.5)', tc:'#333', unlockedBy:'ATMOSPHERE',
        fact:'Your bones are basically calcium. Your teeth too. Milk is basically liquid bones. You\'re welcome for that image.' },
  P:  { id:'P',  name:'Phosphorus', symbol:'P',  sub:'',  emoji:'🔴', tier:'atom', color:'#FF7722', shadow:'rgba(255,119,34,0.5)', tc:'white', unlockedBy:'H2S',
        fact:'Glows in the dark. Essential for DNA. Used in matches and fertilizers. White phosphorus is also terrifyingly flammable. Don\'t touch it.' },
  K:  { id:'K',  name:'Potassium',  symbol:'K',  sub:'',  emoji:'🍌', tier:'atom', color:'#FFCC44', shadow:'rgba(255,200,60,0.5)', tc:'#333', unlockedBy:'BONES',
        fact:'Your heart literally cannot beat without potassium. It\'s in bananas. Eat bananas. Also explodes in water even more violently than sodium.' },
  Mg: { id:'Mg', name:'Magnesium',  symbol:'Mg', sub:'',  emoji:'⚡', tier:'atom', color:'#AADDFF', shadow:'rgba(150,200,255,0.5)', tc:'#333', unlockedBy:'STEEL',
        fact:'Burns with a blindingly bright white flame — so bright you literally cannot look at it. Used in flares and fireworks. Also in your muscles.' },
  Al: { id:'Al', name:'Aluminum',    symbol:'Al', sub:'',  emoji:'📐', tier:'atom', color:'#BBCCDD', shadow:'rgba(180,200,220,0.5)', tc:'#333', unlockedBy:'MgO',
        fact:'The most abundant metal in Earth\'s crust. Used to be more valuable than gold — Napoleon served dinner on aluminum plates to impress guests. Then we figured out cheap extraction and now it wraps leftovers.' },
  Si: { id:'Si', name:'Silicon',     symbol:'Si', sub:'',  emoji:'💎', tier:'atom', color:'#8899BB', shadow:'rgba(130,150,190,0.5)', tc:'white', unlockedBy:'CEMENT',
        fact:'The second most abundant element in Earth\'s crust. Makes up most sand and rocks. Also the thing your phone\'s brain is made of. From beach to processor. What a glow-up.' },
  // ── Wave 3 unlock ──
  F:  { id:'F',  name:'Fluorine',    symbol:'F',  sub:'',  emoji:'🦷', tier:'atom', color:'#44FFAA', shadow:'rgba(68,255,170,0.5)', tc:'#002', unlockedBy:'FeS',
        fact:'The most reactive element in existence. Reacts with almost everything including noble gases. In your toothpaste. Tamed, but not domesticated.' },
  // ── Wave 4 unlocks ──
  Cu: { id:'Cu', name:'Copper',      symbol:'Cu', sub:'',  emoji:'🔶', tier:'atom', color:'#DD7733', shadow:'rgba(221,119,51,0.5)', tc:'white', unlockedBy:'FERTILIZER',
        fact:'First metal humans learned to use — 10,000 years ago. The Statue of Liberty is green because copper oxidizes. Ten millennia of service and counting.' },
  Zn: { id:'Zn', name:'Zinc',        symbol:'Zn', sub:'',  emoji:'🛡️', tier:'atom', color:'#99AABB', shadow:'rgba(153,170,187,0.5)', tc:'#333', unlockedBy:'BAKING_SODA',
        fact:'Coats steel to prevent rust — galvanization. In every sunscreen. Your immune system runs on it. Zinc does the unglamorous work that keeps things alive.' },
  // ── Wave 5 unlocks ──
  Sn: { id:'Sn', name:'Tin',         symbol:'Sn', sub:'',  emoji:'🥫', tier:'atom', color:'#AABBCC', shadow:'rgba(170,187,204,0.5)', tc:'#333', unlockedBy:'BRASS',
        fact:'Symbol Sn from Latin stannum. The Bronze Age wouldn\'t exist without it. When bent, it makes a creaking sound — tin cry. Even metals have feelings.' },
  He: { id:'He', name:'Helium',      symbol:'He', sub:'',  emoji:'🎈', tier:'atom', color:'#DD99FF', shadow:'rgba(221,153,255,0.5)', tc:'#333', unlockedBy:'HF',
        fact:'Second most abundant element in the universe. So light it escapes Earth\'s gravity. We are literally running out of it. Stop wasting it on birthday balloons.' },
  Li: { id:'Li', name:'Lithium',     symbol:'Li', sub:'',  emoji:'🔋', tier:'atom', color:'#FF8866', shadow:'rgba(255,136,102,0.5)', tc:'white', unlockedBy:'NEUTRALIZATION',
        fact:'Lightest metal. Powers every phone, laptop, and EV on Earth. Also treats bipolar disorder. Most important element of the 21st century, no contest.' },
  Br: { id:'Br', name:'Bromine',     symbol:'Br', sub:'',  emoji:'🫗', tier:'atom', color:'#CC4422', shadow:'rgba(204,68,34,0.5)', tc:'white', unlockedBy:'CuSO4',
        fact:'Only nonmetal that\'s liquid at room temperature. Dark reddish-brown. Named from Greek bromos — stench. Accurate naming for once.' },
  I:  { id:'I',  name:'Iodine',      symbol:'I',  sub:'',  emoji:'💜', tier:'atom', color:'#7733AA', shadow:'rgba(119,51,170,0.5)', tc:'white', unlockedBy:'H3PO4',
        fact:'Sublimes into gorgeous purple vapor. Your thyroid needs it to function. Iodized salt saved millions from goiter. A purple crystal preventing neck swelling. Chemistry.' },
  // ── Wave 6 unlocks ──
  Ti: { id:'Ti', name:'Titanium',    symbol:'Ti', sub:'',  emoji:'✈️', tier:'atom', color:'#8899AA', shadow:'rgba(136,153,170,0.5)', tc:'white', unlockedBy:'BRONZE',
        fact:'Strong as steel, half the weight. Aerospace, joint implants, golf clubs. Named after the Titans of Greek mythology. Lives up to it.' },
  Cr: { id:'Cr', name:'Chromium',    symbol:'Cr', sub:'',  emoji:'🪞', tier:'atom', color:'#88AACC', shadow:'rgba(136,170,204,0.5)', tc:'#333', unlockedBy:'Al2O3',
        fact:'Makes things shiny (chrome plating). Makes steel stainless. Ruby red? That\'s chromium impurities in aluminum oxide. One element, three careers.' },
  Mn: { id:'Mn', name:'Manganese',   symbol:'Mn', sub:'',  emoji:'🔩', tier:'atom', color:'#AA7788', shadow:'rgba(170,119,136,0.5)', tc:'white', unlockedBy:'ZnO',
        fact:'Every alkaline battery contains manganese dioxide. Makes steel tougher. Named confusingly similar to magnesium. Chemists were not great at naming things.' },
  Ni: { id:'Ni', name:'Nickel',      symbol:'Ni', sub:'',  emoji:'🪙', tier:'atom', color:'#99AA88', shadow:'rgba(153,170,136,0.5)', tc:'#333', unlockedBy:'LiOH',
        fact:'Named by frustrated miners who found it instead of copper — kupfernickel, devil\'s copper. Now in coins, stainless steel, and rechargeable batteries. Redemption arc.' },
  Ne: { id:'Ne', name:'Neon',        symbol:'Ne', sub:'',  emoji:'💗', tier:'atom', color:'#FF77CC', shadow:'rgba(255,119,204,0.5)', tc:'white', unlockedBy:'Br2',
        fact:'Glows orange-red when electrified. Started a visual revolution with neon signs. Most other neon signs actually use different gases. Neon gets all the credit.' },
  Ar: { id:'Ar', name:'Argon',       symbol:'Ar', sub:'',  emoji:'🫧', tier:'atom', color:'#BB99FF', shadow:'rgba(187,153,255,0.5)', tc:'white', unlockedBy:'Br2',
        fact:'Most abundant noble gas — 0.93% of every breath. Used in light bulbs and welding because it refuses to react with anything. Professional bystander molecule.' },
  // ── Wave 7 unlocks ──
  Co: { id:'Co', name:'Cobalt',      symbol:'Co', sub:'',  emoji:'🔵', tier:'atom', color:'#4466CC', shadow:'rgba(68,102,204,0.5)', tc:'white', unlockedBy:'STAINLESS',
        fact:'Makes glass and ceramics an unforgettable blue. Essential in vitamin B12. Powers EV batteries. Named by miners who blamed goblins for the troublesome ore.' },
  Ag: { id:'Ag', name:'Silver',      symbol:'Ag', sub:'',  emoji:'🥈', tier:'atom', color:'#CCDDEE', shadow:'rgba(204,221,238,0.5)', tc:'#333', unlockedBy:'TiO2',
        fact:'Best electrical and thermal conductor of ALL metals. Kills bacteria on contact. Symbol Ag from Latin argentum. Argentina is literally named after it.' },
  Pb: { id:'Pb', name:'Lead',        symbol:'Pb', sub:'',  emoji:'⚫', tier:'atom', color:'#556677', shadow:'rgba(85,102,119,0.5)', tc:'white', unlockedBy:'MnO2',
        fact:'Romans used lead pipes — plumbing literally comes from plumbum, Latin for lead. Dense, soft, toxic. The Romans didn\'t know that last part. We do.' },
  Ba: { id:'Ba', name:'Barium',      symbol:'Ba', sub:'',  emoji:'💚', tier:'atom', color:'#99DD55', shadow:'rgba(153,221,85,0.5)', tc:'#002', unlockedBy:'NEON_SIGN',
        fact:'Makes fireworks green. Barium sulfate is swallowed for X-rays — opaque to radiation but insoluble, so it passes through safely. Trust the chemistry.' },
  W:  { id:'W',  name:'Tungsten',    symbol:'W',  sub:'',  emoji:'💡', tier:'atom', color:'#667788', shadow:'rgba(102,119,136,0.5)', tc:'white', unlockedBy:'NaBr',
        fact:'Highest melting point of any element — 3,422°C. Light bulb filaments. Symbol W from German Wolfram. Also makes excellent darts and wedding rings.' },
  // ── Wave 8 unlocks ──
  Au: { id:'Au', name:'Gold',        symbol:'Au', sub:'',  emoji:'🥇', tier:'atom', color:'#FFD700', shadow:'rgba(255,215,0,0.5)', tc:'#333', unlockedBy:'MIRROR',
        fact:'Doesn\'t tarnish, corrode, or react with almost anything. All gold ever mined fits in a 21-meter cube. Every atom was forged in a neutron star collision.' },
  Pt: { id:'Pt', name:'Platinum',    symbol:'Pt', sub:'',  emoji:'💍', tier:'atom', color:'#DDDDEE', shadow:'rgba(221,221,238,0.5)', tc:'#333', unlockedBy:'LI_BATTERY',
        fact:'Rarer than gold. Makes catalytic converters work — converts toxic exhaust into less toxic gases. Also in chemotherapy drugs. Saves lives two ways.' },
  Hg: { id:'Hg', name:'Mercury',     symbol:'Hg', sub:'',  emoji:'🌡️', tier:'atom', color:'#CCCCDD', shadow:'rgba(204,204,221,0.5)', tc:'#333', unlockedBy:'SOLDER',
        fact:'Only metal liquid at room temperature. Used in thermometers for centuries. Extremely toxic — accumulates in brain tissue. Mad hatters weren\'t mad for fun.' },
  U:  { id:'U',  name:'Uranium',     symbol:'U',  sub:'',  emoji:'☢️', tier:'atom', color:'#55FF55', shadow:'rgba(85,255,85,0.5)', tc:'#002', unlockedBy:'LIGHT_BULB',
        fact:'92 protons. Mildly radioactive. One kilogram contains the energy of 20,000 tons of coal. Powers submarines, cities, and existential dread simultaneously.' },

  // ── MOLECULES ──
  H2:  { id:'H2',  name:'Hydrogen Gas',  symbol:'H₂',  sub:'gas',  emoji:'🎈', tier:'molecule', color:'#FF9BB5', shadow:'rgba(255,107,157,0.4)', tc:'white',
         fact:'Two hydrogen atoms holding hands. Extremely flammable. The Hindenburg was full of it. We now use helium for blimps. Lesson learned.' },
  O2:  { id:'O2',  name:'Oxygen Gas',    symbol:'O₂',  sub:'gas',  emoji:'🌬️', tier:'molecule', color:'#FF5555', shadow:'rgba(255,68,68,0.4)', tc:'white',
         fact:'What you\'re actually breathing. Trees make it as a waste product. Your waste is their food, their waste is your food. Beautiful.' },
  N2:  { id:'N2',  name:'Nitrogen Gas',  symbol:'N₂',  sub:'gas',  emoji:'🌫️', tier:'molecule', color:'#6699FF', shadow:'rgba(100,150,255,0.4)', tc:'white',
         fact:'78% of every breath. Completely inert — won\'t react with almost anything. Just... there. The most politely useless molecule.' },
  H2O: { id:'H2O', name:'Water',         symbol:'H₂O', sub:'',     emoji:'💧', tier:'molecule', color:'#4488FF', shadow:'rgba(68,136,255,0.5)', tc:'white',
         fact:'Two explosive gases walked into a bar and became the thing fish live in. Water is genuinely the strangest molecule and we\'re made of it.' },
  CO2: { id:'CO2', name:'Carbon Dioxide',symbol:'CO₂', sub:'gas',  emoji:'💨', tier:'molecule', color:'#999999', shadow:'rgba(150,150,150,0.4)', tc:'white',
         fact:'You exhale it. Plants inhale it. What you consider waste, a tree considers breakfast. Try not to feel bad about breathing.' },
  CO:  { id:'CO',  name:'Carbon Monoxide',symbol:'CO', sub:'gas',  emoji:'⚠️', tier:'molecule', color:'#777777', shadow:'rgba(120,120,120,0.4)', tc:'white', danger:true,
         fact:'Colorless. Odorless. Undetectable by human senses. Lethal. Bonds to your hemoglobin 200x stronger than oxygen, quietly suffocating you from the inside. This is why we have smoke detectors.' },
  NaCl:{ id:'NaCl',name:'Table Salt',    symbol:'NaCl',sub:'',     emoji:'🧂', tier:'molecule', color:'#EEEEEE', shadow:'rgba(200,200,200,0.4)', tc:'#333',
         fact:'Sodium (explodes in water) + Chlorine (poison gas) = the thing you put on fries. Chemistry is basically magic.' },
  NH3: { id:'NH3', name:'Ammonia',       symbol:'NH₃', sub:'',     emoji:'🌿', tier:'molecule', color:'#55EE77', shadow:'rgba(85,238,119,0.4)', tc:'#002',
         fact:'Smells absolutely horrible. Also responsible for feeding half the humans alive today via fertilizers. You\'re welcome, humanity.' },
  H2S: { id:'H2S', name:'Hydrogen Sulfide',symbol:'H₂S',sub:'gas', emoji:'🦨', tier:'molecule', color:'#BBAA00', shadow:'rgba(190,170,0,0.4)', tc:'white', danger:true,
         fact:'The molecule responsible for farts, rotten eggs, and swamps. Also naturally occurring in volcanoes. In high concentrations: instantly deadly. Low concentrations: merely embarrassing.' },
  SO2: { id:'SO2', name:'Sulfur Dioxide',symbol:'SO₂', sub:'gas',  emoji:'🌋', tier:'molecule', color:'#FFAA33', shadow:'rgba(255,170,51,0.4)', tc:'#332',
         fact:'What volcanoes breathe out. Turns into sulfuric acid when it hits rain. Responsible for acid rain that kills forests. Volcanoes don\'t care.' },
  HCl: { id:'HCl', name:'Hydrochloric Acid',symbol:'HCl',sub:'acid',emoji:'⚗️',tier:'molecule', color:'#77FFBB', shadow:'rgba(100,255,180,0.4)', tc:'#002',
         fact:'Your stomach makes this to digest food. Strong enough to dissolve metal. The reason you don\'t dissolve yourself is a thin layer of mucus. Think about that at dinner.' },
  FeO: { id:'FeO', name:'Iron Oxide (Rust)',symbol:'FeO',sub:'',   emoji:'🟤', tier:'molecule', color:'#CC4422', shadow:'rgba(200,68,34,0.4)', tc:'white',
         fact:'Technically your iron is rotting. Slowly. The Titanic is slowly becoming rust on the ocean floor. Everything returns to dust, or in this case, oxide.' },
  CH4: { id:'CH4', name:'Methane',         symbol:'CH₄', sub:'gas',  emoji:'🐄', tier:'molecule', color:'#88CC44', shadow:'rgba(130,200,68,0.4)', tc:'white',
         fact:'Swamp gas. Cow farts. Natural gas. The simplest hydrocarbon — one carbon surrounded by four hydrogens. Also 80x more potent than CO₂ as a greenhouse gas. Cows are literally a climate problem.' },
  MgO: { id:'MgO', name:'Magnesium Oxide', symbol:'MgO', sub:'',     emoji:'💡', tier:'molecule', color:'#EEEEFF', shadow:'rgba(220,220,255,0.5)', tc:'#333',
         fact:'Burns with a blindingly white flame. So bright it was used in early camera flashes and stage lighting. That white stripe on a firework? Magnesium oxide. You\'re welcome, Fourth of July.' },
  KOH: { id:'KOH', name:'Potassium Hydroxide',symbol:'KOH',sub:'',  emoji:'🧴', tier:'molecule', color:'#FFDD77', shadow:'rgba(255,220,120,0.4)', tc:'#333',
         fact:'Caustic potash. Used to make liquid soap, biodiesel, and alkaline batteries. The reaction of potassium in water is violent enough to ignite the hydrogen produced. Don\'t try this at home. Or anywhere.' },
  NaOH:{ id:'NaOH',name:'Sodium Hydroxide',symbol:'NaOH',sub:'',    emoji:'🧼', tier:'molecule', color:'#DDDDFF', shadow:'rgba(200,200,255,0.4)', tc:'#333',
         fact:'Lye. Caustic soda. Dissolves organic matter including... you. Used to make soap, unclog drains, and cure olives. One of these things is not like the others.' },
  FeCl2:{ id:'FeCl2',name:'Iron(II) Chloride',symbol:'FeCl₂',sub:'',emoji:'🟢', tier:'molecule', color:'#55AA77', shadow:'rgba(85,170,119,0.4)', tc:'white',
         fact:'Green crystals formed when iron dissolves in hydrochloric acid, bubbling hydrogen. Used in water treatment to remove impurities. The iron sacrifices itself so your water stays clean. Noble.' },
  CaCl2:{ id:'CaCl2',name:'Calcium Chloride',symbol:'CaCl₂',sub:'', emoji:'🧊', tier:'molecule', color:'#99BBDD', shadow:'rgba(150,190,220,0.4)', tc:'white',
         fact:'The stuff they dump on icy roads. Absorbs moisture so aggressively it dissolves itself. Also used in cheese-making. Salt\'s more ambitious cousin.' },
  NO:  { id:'NO',  name:'Nitric Oxide',    symbol:'NO',  sub:'gas',  emoji:'❤️', tier:'molecule', color:'#FF6677', shadow:'rgba(255,100,120,0.4)', tc:'white',
         fact:'A signaling molecule in your body that relaxes blood vessels. Won the Nobel Prize in 1998. Also produced by lightning strikes. Your heart and thunderstorms run on the same chemistry.' },
  SiO2:{ id:'SiO2',name:'Silicon Dioxide', symbol:'SiO₂',sub:'',    emoji:'🏖️', tier:'molecule', color:'#DDCC88', shadow:'rgba(220,200,130,0.4)', tc:'#333',
         fact:'Sand. Glass. Quartz. The most common mineral on Earth\'s surface. Melt it, cool it fast, and you get glass. Humanity\'s been doing this for 5,000 years. We still think it\'s cool.' },
  // ── New Molecules ──
  LiOH:{ id:'LiOH',name:'Lithium Hydroxide',symbol:'LiOH',sub:'',  emoji:'🧪', tier:'molecule', color:'#FFAA99', shadow:'rgba(255,170,153,0.4)', tc:'white',
         fact:'Used in spacecraft to scrub CO₂ from the air. Also in lithium grease. Surprisingly mundane for containing the most exciting metal of our century.' },
  HF:  { id:'HF',  name:'Hydrofluoric Acid',symbol:'HF', sub:'acid', emoji:'⚗️', tier:'molecule', color:'#66FFCC', shadow:'rgba(102,255,204,0.4)', tc:'#002',
         fact:'Weak acid by textbook definition but TERRIFYINGLY dangerous. Penetrates skin painlessly, then dissolves bone from inside. Don\'t let the word weak fool you.' },
  HBr: { id:'HBr', name:'Hydrobromic Acid', symbol:'HBr',sub:'acid', emoji:'⚗️', tier:'molecule', color:'#DD8877', shadow:'rgba(221,136,119,0.4)', tc:'white',
         fact:'Strong acid. Used to make various bromide compounds. Less famous than HCl but just as capable. The middle child of the hydrogen halide acids.' },
  HI:  { id:'HI',  name:'Hydroiodic Acid',  symbol:'HI', sub:'acid', emoji:'⚗️', tier:'molecule', color:'#9966BB', shadow:'rgba(153,102,187,0.4)', tc:'white',
         fact:'Strongest of the hydrogen halide acids. A powerful reducing agent. Used to make iodide salts. The quiet overachiever of the halogen family.' },
  NaF: { id:'NaF', name:'Sodium Fluoride',  symbol:'NaF',sub:'',    emoji:'🦷', tier:'molecule', color:'#AAFFDD', shadow:'rgba(170,255,221,0.4)', tc:'#002',
         fact:'The fluoride in your toothpaste. Strengthens enamel by converting hydroxyapatite to fluorapatite. Chemistry protecting your smile since 1914.' },
  NaBr:{ id:'NaBr',name:'Sodium Bromide',   symbol:'NaBr',sub:'',   emoji:'💊', tier:'molecule', color:'#DDAA99', shadow:'rgba(221,170,153,0.4)', tc:'#333',
         fact:'Used as a sedative in the 19th century. Given to soldiers in tea to reduce... enthusiasm. The word bromide became slang for something boring.' },
  NaI: { id:'NaI', name:'Sodium Iodide',    symbol:'NaI',sub:'',    emoji:'💜', tier:'molecule', color:'#AA88CC', shadow:'rgba(170,136,204,0.4)', tc:'white',
         fact:'Scintillation detector material — flashes when radiation hits it. Used in nuclear medicine to detect gamma rays. Literally glows with excitement.' },
  KCl: { id:'KCl', name:'Potassium Chloride',symbol:'KCl',sub:'',   emoji:'🧂', tier:'molecule', color:'#FFDD88', shadow:'rgba(255,221,136,0.4)', tc:'#333',
         fact:'Salt substitute for people watching sodium intake. Also used in lethal injections. And fertilizer. One molecule, very different contexts.' },
  CuO: { id:'CuO', name:'Copper Oxide',     symbol:'CuO',sub:'',    emoji:'🟤', tier:'molecule', color:'#664422', shadow:'rgba(102,68,34,0.4)', tc:'white',
         fact:'Black powder. Why the Statue of Liberty turned green — copper reacts with air over decades. Slow-motion chemistry visible from space.' },
  ZnO: { id:'ZnO', name:'Zinc Oxide',       symbol:'ZnO',sub:'',    emoji:'🧴', tier:'molecule', color:'#EEEEDD', shadow:'rgba(238,238,221,0.4)', tc:'#333',
         fact:'That white stuff on lifeguards\' noses. Blocks UV radiation. Also in rubber and semiconductors. From sunscreen to circuits.' },
  TiO2:{ id:'TiO2',name:'Titanium Dioxide', symbol:'TiO₂',sub:'',   emoji:'⬜', tier:'molecule', color:'#FAFAFA', shadow:'rgba(200,200,200,0.4)', tc:'#333',
         fact:'The whitest white pigment. In every white paint, sunscreen, and toothpaste on Earth. You see it everywhere but never notice. Invisible ubiquity.' },
  Cr2O3:{id:'Cr2O3',name:'Chromium Oxide',  symbol:'Cr₂O₃',sub:'',  emoji:'🟢', tier:'molecule', color:'#228833', shadow:'rgba(34,136,51,0.4)', tc:'white',
         fact:'Deep green pigment used since ancient Egypt. Also an abrasive for polishing metals. That green on military vehicles? Chromium oxide. 4,000 years of green.' },
  MnO2:{ id:'MnO2',name:'Manganese Dioxide',symbol:'MnO₂',sub:'',   emoji:'🔋', tier:'molecule', color:'#443322', shadow:'rgba(68,51,34,0.4)', tc:'white',
         fact:'Inside every alkaline battery. Also used as pigment in cave paintings 30,000 years ago. Prehistoric humans and Duracell — same molecule.' },
  Al2O3:{id:'Al2O3',name:'Corundum',         symbol:'Al₂O₃',sub:'',  emoji:'💎', tier:'molecule', color:'#DDEEFF', shadow:'rgba(221,238,255,0.4)', tc:'#333',
         fact:'Sapphires and rubies are this with impurities. Chromium makes ruby, iron and titanium make sapphire. Same mineral, different sparkle, wildly different price.' },
  BaO: { id:'BaO', name:'Barium Oxide',     symbol:'BaO',sub:'',    emoji:'🟡', tier:'molecule', color:'#88CC44', shadow:'rgba(136,204,68,0.4)', tc:'#002',
         fact:'Used to produce hydrogen peroxide historically. Absorbs moisture and CO₂ from air aggressively. A hygroscopic overachiever.' },
  WO3: { id:'WO3', name:'Tungsten Trioxide',symbol:'WO₃',sub:'',    emoji:'🟡', tier:'molecule', color:'#CCCC44', shadow:'rgba(204,204,68,0.4)', tc:'#333',
         fact:'Yellow powder used in electrochromic smart windows — apply voltage and it tints. Your future sunglasses are made of tungsten chemistry.' },
  HgO: { id:'HgO', name:'Mercury Oxide',    symbol:'HgO',sub:'',    emoji:'🟠', tier:'molecule', color:'#FF6633', shadow:'rgba(255,102,51,0.4)', tc:'white',
         fact:'Red powder. Priestley heated this in 1774 and discovered oxygen. One of the most historically important chemical reactions ever performed. In a shed.' },
  PbO: { id:'PbO', name:'Lead Oxide',       symbol:'PbO',sub:'',    emoji:'🟡', tier:'molecule', color:'#DDAA33', shadow:'rgba(221,170,51,0.4)', tc:'#333',
         fact:'Litharge. Yellow powder used in lead-acid batteries, pottery glazes, and Renaissance paintings. Beautiful and toxic. Artists didn\'t know. We do.' },
  UO2: { id:'UO2', name:'Uranium Dioxide',  symbol:'UO₂',sub:'',    emoji:'☢️', tier:'molecule', color:'#556633', shadow:'rgba(85,102,51,0.4)', tc:'white',
         fact:'The actual fuel in nuclear reactors. Dark brown ceramic pellets stacked in rods. One pellet has the energy of 17,000 cubic feet of natural gas.' },
  FeS: { id:'FeS', name:'Iron Sulfide',     symbol:'FeS',sub:'',    emoji:'🌑', tier:'molecule', color:'#555544', shadow:'rgba(85,85,68,0.4)', tc:'white',
         fact:'Strike it with steel and it sparks — that\'s how flint-and-steel fire starters work. Also the starting point for making sulfuric acid industrially.' },
  FeS2:{ id:'FeS2',name:'Pyrite',           symbol:'FeS₂',sub:'fool\'s gold',emoji:'✨',tier:'molecule',color:'#CCAA44',shadow:'rgba(204,170,68,0.4)',tc:'#333',
         fact:'Fool\'s gold. Shiny, metallic, golden — and worthless. Tricked countless prospectors. Named from Greek pyr (fire) because it sparks when struck.' },
  CuS: { id:'CuS', name:'Covellite',        symbol:'CuS',sub:'',    emoji:'🖤', tier:'molecule', color:'#223344', shadow:'rgba(34,51,68,0.4)', tc:'white',
         fact:'Black mineral with an iridescent blue-purple sheen when light hits it just right. One of the most beautiful minerals. Nature showing off.' },
  ZnS: { id:'ZnS', name:'Zinc Sulfide',     symbol:'ZnS',sub:'',    emoji:'🌟', tier:'molecule', color:'#DDDDAA', shadow:'rgba(221,221,170,0.4)', tc:'#333',
         fact:'Phosphorescent — glows in the dark. Those stars on your childhood ceiling? Zinc sulfide. Also used in early cathode ray tube TVs. Retro glow.' },
  PbS: { id:'PbS', name:'Galena',           symbol:'PbS',sub:'galena',emoji:'⬛',tier:'molecule', color:'#444455', shadow:'rgba(68,68,85,0.4)', tc:'white',
         fact:'Lead sulfide. The original semiconductor — galena crystal radios in the 1900s were the first radios ever. Shiny cubic crystals. Dangerously pretty.' },
  HNO3:{ id:'HNO3',name:'Nitric Acid',      symbol:'HNO₃',sub:'acid',emoji:'⚗️',tier:'molecule',color:'#FF8844',shadow:'rgba(255,136,68,0.4)',tc:'white', danger:true,
         fact:'⚠️ DANGER ZONE. Strong acid that turns skin yellow on contact. Used to make fertilizer AND explosives. Corrodes most metals. Stains everything it touches.' },
  H3PO4:{id:'H3PO4',name:'Phosphoric Acid', symbol:'H₃PO₄',sub:'acid',emoji:'🥤',tier:'molecule',color:'#DDBB88',shadow:'rgba(221,187,136,0.4)',tc:'#333',
         fact:'In every can of Coca-Cola. Also used to rust-proof steel and make fertilizers. pH 2.8 in your soda. Your teeth are not thrilled about this.' },
  AgCl:{ id:'AgCl',name:'Silver Chloride',   symbol:'AgCl',sub:'',   emoji:'📷', tier:'molecule', color:'#DDDDCC', shadow:'rgba(221,221,204,0.4)', tc:'#333',
         fact:'Turns dark when exposed to light. This is literally how photography works. Silver halides capture photons. Every analog photo is frozen chemistry.' },
  AgNO3:{id:'AgNO3',name:'Silver Nitrate',   symbol:'AgNO₃',sub:'',  emoji:'🩹', tier:'molecule', color:'#CCCCBB', shadow:'rgba(204,204,187,0.4)', tc:'#333',
         fact:'Cauterizes wounds on contact. Makes invisible ink that appears when heated. Stains skin permanently black. Wear gloves. I mean it.' },
  CuCl2:{id:'CuCl2',name:'Copper Chloride',  symbol:'CuCl₂',sub:'',  emoji:'💧', tier:'molecule', color:'#33BBAA', shadow:'rgba(51,187,170,0.4)', tc:'#002',
         fact:'Bright turquoise in solution. Makes flames green in fireworks. Also a catalyst and wood preservative. Chemistry\'s favorite color.' },
  CuSO4:{id:'CuSO4',name:'Copper Sulfate',   symbol:'CuSO₄',sub:'',  emoji:'💎', tier:'molecule', color:'#3388DD', shadow:'rgba(51,136,221,0.4)', tc:'white',
         fact:'Brilliant blue crystals. Used in Bordeaux mixture to protect vineyards from fungus since 1885. Also the electrolyte in copper electroplating.' },
  PbCl2:{id:'PbCl2',name:'Lead Chloride',     symbol:'PbCl₂',sub:'',  emoji:'⬜', tier:'molecule', color:'#DDDDBB', shadow:'rgba(221,221,187,0.4)', tc:'#333',
         fact:'White crystals. One of the few soluble lead compounds. Historically used in white lead paint — gorgeous pigment, horrible poisoning.' },
  NiO: { id:'NiO', name:'Nickel Oxide',      symbol:'NiO',sub:'',    emoji:'🟢', tier:'molecule', color:'#77AA66', shadow:'rgba(119,170,102,0.4)', tc:'white',
         fact:'Green powder used in ceramics for centuries. Key component in nickel-cadmium batteries. Unassuming but industrially vital.' },
  CoO: { id:'CoO', name:'Cobalt Oxide',      symbol:'CoO',sub:'',    emoji:'🔵', tier:'molecule', color:'#3355AA', shadow:'rgba(51,85,170,0.4)', tc:'white',
         fact:'Deep blue. Used to color glass since ancient Egypt — cobalt blue beads found in tombs from 2600 BCE. 4,600 years and we still can\'t resist that blue.' },
  SnO2:{ id:'SnO2',name:'Tin Dioxide',       symbol:'SnO₂',sub:'',   emoji:'📱', tier:'molecule', color:'#CCCCBB', shadow:'rgba(204,204,187,0.4)', tc:'#333',
         fact:'Cassiterite — the main tin ore. Used in transparent conductive coatings on touchscreens. Your phone screen has tin oxide on it right now.' },
  I2:  { id:'I2',  name:'Iodine Crystals',   symbol:'I₂', sub:'',    emoji:'💜', tier:'molecule', color:'#553388', shadow:'rgba(85,51,136,0.4)', tc:'white',
         fact:'Dark purple-black crystals that sublime directly into violet vapor. Used as antiseptic. Stains absolutely everything. Beautiful and inconvenient.' },

  // ── COMPOUNDS ──
  SALT_WATER:    { id:'SALT_WATER',    name:'Salt Water',      symbol:'NaCl·H₂O', sub:'', emoji:'🌊', tier:'compound', color:'#1166BB', shadow:'rgba(17,102,187,0.5)', tc:'white',
                   fact:'The ocean is 3.5% salt, which is why you can\'t drink it. Your kidneys would need MORE water to process it than you\'d gain. The ocean is actually thirsty.' },
  CARBONIC_ACID: { id:'CARBONIC_ACID', name:'Carbonic Acid',   symbol:'H₂CO₃',   sub:'', emoji:'🥤', tier:'compound', color:'#99DDFF', shadow:'rgba(153,221,255,0.4)', tc:'#333',
                   fact:'This is what makes soda fizzy. CO₂ dissolves in water under pressure. Open the bottle, release the pressure — the CO₂ escapes as bubbles. You\'re basically releasing tiny screaming gas molecules.' },
  ACID_RAIN:     { id:'ACID_RAIN',     name:'Acid Rain',       symbol:'H₂SO₃',   sub:'', emoji:'🌧️', tier:'compound', color:'#AAAA33', shadow:'rgba(170,170,51,0.4)', tc:'white',
                   fact:'SO₂ from factories and volcanoes dissolves in rain to make sulfurous acid. Falls from the sky. Kills trees. Dissolves limestone statues. Fun for nobody.' },
  PHOTOSYNTHESIS:{ id:'PHOTOSYNTHESIS',name:'Photosynthesis',  symbol:'CO₂+H₂O→C₆H₁₂O₆',sub:'',emoji:'🌱',tier:'compound',color:'#33BB55',shadow:'rgba(51,187,85,0.5)',tc:'white',
                   fact:'Plants eat CO₂ and water, use sunlight as energy, and poop out oxygen and sugar. Your entire food chain depends on this one reaction. Plants are out here doing the most.' },
  OCEAN:         { id:'OCEAN',         name:'The Ocean',       symbol:'H₂O+NaCl', sub:'', emoji:'🌍', tier:'compound', color:'#005599', shadow:'rgba(0,85,153,0.5)', tc:'white',
                   fact:'The ocean covers 71% of Earth and we\'ve explored less than 20% of it. There are creatures down there we\'ve never seen. The ocean keeps its secrets.' },
  STEEL:         { id:'STEEL',         name:'Steel',           symbol:'Fe+C',      sub:'', emoji:'🗼', tier:'compound', color:'#7788AA', shadow:'rgba(100,120,160,0.4)', tc:'white',
                   fact:'Iron with a tiny bit of carbon — 0.2 to 2%. That\'s it. That small addition makes it 1000x stronger. The Eiffel Tower, skyscrapers, your car — all just iron with a pinch of carbon.' },
  BONES:         { id:'BONES',         name:'Bone',            symbol:'Ca₃(PO₄)₂',sub:'', emoji:'🦴', tier:'compound', color:'#EEEEBB', shadow:'rgba(220,220,180,0.4)', tc:'#333',
                   fact:'Your skeleton is made of calcium phosphate — the exact same mineral found in rocks. You are literally made of rock. Your skeleton completely replaces itself every 10 years.' },
  ATMOSPHERE:    { id:'ATMOSPHERE',    name:'Atmosphere',      symbol:'N₂+O₂+CO₂',sub:'', emoji:'🌤️', tier:'compound', color:'#3366EE', shadow:'rgba(51,102,238,0.5)', tc:'white',
                   fact:'A thin shell of gas clinging to Earth by gravity. Without it, all water boils away, radiation fries everything, and it\'s -270°C at night. The atmosphere is doing a LOT of heavy lifting.' },
  STOMACH_ACID:  { id:'STOMACH_ACID',  name:'Stomach Acid',    symbol:'HCl(aq)',   sub:'', emoji:'🫃', tier:'compound', color:'#44EE77', shadow:'rgba(68,238,119,0.4)', tc:'#002',
                   fact:'pH of 1.5 to 3.5. Strong enough to dissolve a razor blade given enough time. Your stomach lining is protected by a thin layer of mucus. If that ever fails — that\'s an ulcer. Don\'t think about it.' },
  LIFE:          { id:'LIFE',          name:'Life!',           symbol:'C+H+O+N+P+S',sub:'',emoji:'🧬',tier:'compound',color:'#FF44AA',shadow:'rgba(255,68,170,0.6)',tc:'white',
                   fact:'You did it. All life on Earth is built from 6 elements: Carbon, Hydrogen, Oxygen, Nitrogen, Phosphorus, Sulfur. You are a walking chemistry experiment. You are literally stardust that learned to think.' },
  CaO:          { id:'CaO',          name:'Quicklime',       symbol:'CaO',      sub:'', emoji:'🔥', tier:'compound', color:'#EECC88', shadow:'rgba(230,200,130,0.4)', tc:'#333',
                   fact:'Calcium oxide. Made by heating limestone to 900°C. Reacts so violently with water it glows white-hot. Romans used it in construction. Also called "hot lime" because it literally is.' },
  CaCO3:        { id:'CaCO3',        name:'Limestone',       symbol:'CaCO₃',    sub:'', emoji:'🪨', tier:'compound', color:'#CCBB99', shadow:'rgba(200,190,150,0.4)', tc:'#333',
                   fact:'Seashells, chalk, marble, limestone — all calcium carbonate. The White Cliffs of Dover are made of this. Billions of years of sea creatures compressed into rock. You are standing on ancient graves.' },
  FERTILIZER:   { id:'FERTILIZER',   name:'Fertilizer',      symbol:'CO(NH₂)₂', sub:'', emoji:'🌾', tier:'compound', color:'#77BB44', shadow:'rgba(119,187,68,0.5)', tc:'white',
                   fact:'The Haber-Bosch process turns atmospheric nitrogen into ammonia fertilizer. It feeds half the humans alive today. Fritz Haber won a Nobel Prize for it. He also invented chemical weapons. History is complicated.' },
  CEMENT:       { id:'CEMENT',       name:'Cement',          symbol:'Ca(OH)₂',  sub:'', emoji:'🏗️', tier:'compound', color:'#AAAAAA', shadow:'rgba(160,160,160,0.4)', tc:'white',
                   fact:'Quicklime + water = calcium hydroxide = cement. The Romans figured this out 2000 years ago. Their concrete is STILL standing. Modern concrete crumbles in 50 years. We went backwards.' },
  BAKING_SODA:  { id:'BAKING_SODA',  name:'Baking Soda',     symbol:'NaHCO₃',   sub:'', emoji:'🧁', tier:'compound', color:'#FFEEDD', shadow:'rgba(255,230,210,0.4)', tc:'#333',
                   fact:'Sodium bicarbonate. Makes cakes rise, settles stomachs, puts out grease fires, and deodorizes your fridge. The most useful boring-looking white powder in your kitchen. Probably.' },
  NEUTRALIZATION:{ id:'NEUTRALIZATION',name:'Neutralization', symbol:'NaOH+HCl', sub:'', emoji:'⚖️', tier:'compound', color:'#AADDCC', shadow:'rgba(150,220,190,0.4)', tc:'#333',
                   fact:'Acid meets base. They cancel out. Exothermic — releases heat. What\'s left? Salt and water. Every acid-base reaction is secretly just making flavored salt water. Chemistry\'s great punchline.' },
  GLASS:        { id:'GLASS',        name:'Glass',           symbol:'SiO₂+Na₂O',sub:'', emoji:'🪟', tier:'compound', color:'#AADDEE', shadow:'rgba(150,220,240,0.4)', tc:'#333',
                   fact:'Melt sand with soda ash, cool it fast, and the atoms freeze in disorder — no crystal structure. That\'s glass. A liquid pretending to be a solid. Transparent because photons pass right through the chaos.' },
  SMOG:         { id:'SMOG',         name:'Smog',            symbol:'NO₂+SO₂',  sub:'', emoji:'🏭', tier:'compound', color:'#887744', shadow:'rgba(130,120,70,0.4)', tc:'white',
                   fact:'Nitrogen dioxide + sulfur dioxide + sunlight = photochemical smog. The brown haze over cities. London\'s Great Smog of 1952 killed 12,000 people in four days. Clean air is not optional.' },
  // ── New Compounds ──
  Mg_OH_2:      { id:'Mg_OH_2',      name:'Milk of Magnesia', symbol:'Mg(OH)₂', sub:'', emoji:'🥛', tier:'compound', color:'#EEEEFF', shadow:'rgba(238,238,255,0.4)', tc:'#333',
                   fact:'Antacid and laxative. Neutralizes stomach acid. Named because it looks like milk. Your stomach\'s best friend at 2 AM after questionable decisions.' },
  Al_OH_3:      { id:'Al_OH_3',      name:'Antacid',          symbol:'Al(OH)₃', sub:'', emoji:'💊', tier:'compound', color:'#EEDDCC', shadow:'rgba(238,221,204,0.4)', tc:'#333',
                   fact:'Aluminum hydroxide. Active ingredient in Maalox. Neutralizes acid without being absorbed. Also purifies water by trapping particles. Multitasker.' },
  Ba_OH_2:      { id:'Ba_OH_2',      name:'Barium Hydroxide', symbol:'Ba(OH)₂', sub:'', emoji:'🧪', tier:'compound', color:'#AADD88', shadow:'rgba(170,221,136,0.4)', tc:'#002',
                   fact:'Gets extremely cold when dissolved — endothermic enough to freeze water on contact. The opposite of most reactions. Chemistry doing the unexpected.' },
  MgCO3:        { id:'MgCO3',        name:'Climber\'s Chalk', symbol:'MgCO₃',   sub:'', emoji:'🏔️', tier:'compound', color:'#DDDDCC', shadow:'rgba(221,221,204,0.4)', tc:'#333',
                   fact:'That white powder on every rock climber\'s hands. Absorbs moisture, improves grip, prevents sweaty palms. Magnesite keeping you on the wall.' },
  CuCO3:        { id:'CuCO3',        name:'Verdigris',        symbol:'CuCO₃',   sub:'', emoji:'🗽', tier:'compound', color:'#44AA88', shadow:'rgba(68,170,136,0.4)', tc:'white',
                   fact:'The green patina on old copper — Statue of Liberty, church roofs, ancient bronze. Copper + air + time = that iconic teal. Slow-motion art.' },
  BaCO3:        { id:'BaCO3',        name:'Barium Carbonate', symbol:'BaCO₃',   sub:'', emoji:'🐀', tier:'compound', color:'#BBDD99', shadow:'rgba(187,221,153,0.4)', tc:'#002',
                   fact:'Used as rat poison — toxic barium released by stomach acid. Also in ceramics and glass. Named from Greek barys meaning heavy. Not a fun compound.' },
  BaSO4:        { id:'BaSO4',        name:'Barium Meal',      symbol:'BaSO₄',   sub:'', emoji:'🏥', tier:'compound', color:'#EEEEEE', shadow:'rgba(238,238,238,0.4)', tc:'#333',
                   fact:'Swallowed before X-rays — opaque to radiation, shows up bright white. Completely insoluble so it passes through safely. The one barium you can eat.' },
  Na2CO3:       { id:'Na2CO3',       name:'Soda Ash',         symbol:'Na₂CO₃',  sub:'', emoji:'🧹', tier:'compound', color:'#EEEEFF', shadow:'rgba(238,238,255,0.4)', tc:'#333',
                   fact:'Washing soda. Used to make glass, soap, and paper. Ancient Egyptians used it for mummification. Cleaning since 3000 BCE.' },
  KNO3:         { id:'KNO3',         name:'Saltpeter',        symbol:'KNO₃',    sub:'', emoji:'💥', tier:'compound', color:'#FFEECC', shadow:'rgba(255,238,204,0.4)', tc:'#333',
                   fact:'The oxidizer in gunpowder. Also a food preservative for cured meats. Also a fertilizer. Destruction, preservation, and growth. One molecule.' },
  METHANOL:     { id:'METHANOL',     name:'Methanol',         symbol:'CH₃OH',   sub:'', emoji:'🧪', tier:'compound', color:'#88CCAA', shadow:'rgba(136,204,170,0.4)', tc:'#002',
                   fact:'Wood alcohol. Looks and smells like ethanol but causes blindness and death. Used as fuel and antifreeze. The evil twin of drinking alcohol.' },
  ETHANOL:      { id:'ETHANOL',      name:'Ethanol',          symbol:'C₂H₅OH',  sub:'', emoji:'🍷', tier:'compound', color:'#FFCC88', shadow:'rgba(255,204,136,0.4)', tc:'#333',
                   fact:'The alcohol in every drink. Yeast eats sugar, excretes this. 9,000 years of brewing. We literally domesticated fungus to make it for us.' },
  ETHYLENE:     { id:'ETHYLENE',     name:'Ethylene',         symbol:'C₂H₄',    sub:'gas', emoji:'🍎', tier:'compound', color:'#AADD55', shadow:'rgba(170,221,85,0.4)', tc:'#002',
                   fact:'The fruit-ripening hormone. One rotten apple spoils the bunch via ethylene. Also the most-produced organic compound on Earth. Plastics start here.' },
  ACETYLENE:    { id:'ACETYLENE',    name:'Acetylene',        symbol:'C₂H₂',    sub:'gas', emoji:'🔥', tier:'compound', color:'#FFBB44', shadow:'rgba(255,187,68,0.4)', tc:'#333',
                   fact:'Burns at 3,300°C — hot enough to cut steel with oxy-acetylene torches. Made by dropping water on calcium carbide. Miners\' lamps used this.' },
  ACETIC_ACID:  { id:'ACETIC_ACID',  name:'Vinegar',          symbol:'CH₃COOH', sub:'', emoji:'🫙', tier:'compound', color:'#DDCC88', shadow:'rgba(221,204,136,0.4)', tc:'#333',
                   fact:'Acetic acid — what makes vinegar sour. Bacteria oxidize ethanol to make it. Wine gone bad, repurposed. Oldest chemical trick in the book.' },
  FORMALDEHYDE: { id:'FORMALDEHYDE', name:'Formaldehyde',     symbol:'CH₂O',    sub:'', emoji:'🏥', tier:'compound', color:'#CCDDBB', shadow:'rgba(204,221,187,0.4)', tc:'#333',
                   fact:'Preserves biological specimens. That smell in biology class. Also naturally produced by your body in small amounts. Everywhere and invisible.' },
  GLUCOSE:      { id:'GLUCOSE',      name:'Glucose',          symbol:'C₆H₁₂O₆',sub:'', emoji:'🍬', tier:'compound', color:'#FFDD66', shadow:'rgba(255,221,102,0.4)', tc:'#333',
                   fact:'Blood sugar. The fuel your cells burn. Every carb you eat becomes this. Plants make it from sunlight via photosynthesis. The molecule of energy.' },
  SOAP:         { id:'SOAP',         name:'Soap',             symbol:'RCOONa',  sub:'', emoji:'🧼', tier:'compound', color:'#DDDDFF', shadow:'rgba(221,221,255,0.4)', tc:'#333',
                   fact:'Fat + lye = soap. One end loves water, the other loves oil. Surrounds grease, rips it off surfaces. Chemistry\'s most useful invention after fire.' },
  PROPANE:      { id:'PROPANE',      name:'Propane',          symbol:'C₃H₈',    sub:'gas', emoji:'🔥', tier:'compound', color:'#FF9944', shadow:'rgba(255,153,68,0.4)', tc:'white',
                   fact:'BBQ fuel. Three carbons in a chain. Liquefies under modest pressure. Clean-burning. Hank Hill would be proud you discovered this.' },
  BUTANE:       { id:'BUTANE',       name:'Butane',           symbol:'C₄H₁₀',   sub:'gas', emoji:'🔥', tier:'compound', color:'#FF8833', shadow:'rgba(255,136,51,0.4)', tc:'white',
                   fact:'Lighter fluid. Four carbons. That sloshing in a disposable lighter is liquid butane. Also a propellant in aerosol cans. Pocketable chemistry.' },
  BRONZE:       { id:'BRONZE',       name:'Bronze',           symbol:'Cu+Sn',   sub:'', emoji:'🏺', tier:'compound', color:'#CD7F32', shadow:'rgba(205,127,50,0.5)', tc:'white',
                   fact:'Copper + tin. Started the Bronze Age around 3300 BCE. Harder than copper, casts better. Made swords, plows, and civilization. An alloy that changed history.' },
  BRASS:        { id:'BRASS',        name:'Brass',            symbol:'Cu+Zn',   sub:'', emoji:'🎺', tier:'compound', color:'#DDAA44', shadow:'rgba(221,170,68,0.4)', tc:'#333',
                   fact:'Copper + zinc. Musical instruments, doorknobs, ammunition casings. Antimicrobial — bacteria die on brass surfaces within hours. Self-sterilizing metal.' },
  STAINLESS:    { id:'STAINLESS',    name:'Stainless Steel',  symbol:'Fe+Cr',   sub:'', emoji:'🔪', tier:'compound', color:'#AABBCC', shadow:'rgba(170,187,204,0.4)', tc:'#333',
                   fact:'Steel + chromium (min 10.5%). The chromium forms an oxide layer that heals itself when scratched. Self-repairing metal. Invented by accident in 1913.' },
  SOLDER:       { id:'SOLDER',       name:'Solder',           symbol:'Sn+Pb',   sub:'', emoji:'🔌', tier:'compound', color:'#999988', shadow:'rgba(153,153,136,0.4)', tc:'#333',
                   fact:'Tin + lead. Melts at low temperature to join electronics. Every circuit board connection is a tiny metallurgical joint holding your technology together.' },
  BATTERY:      { id:'BATTERY',      name:'Voltaic Cell',     symbol:'Zn+Cu',   sub:'', emoji:'🔋', tier:'compound', color:'#DDCC44', shadow:'rgba(221,204,68,0.4)', tc:'#333',
                   fact:'Zinc + copper in electrolyte. Volta stacked these in 1800 — the first battery. Electrons flow from zinc to copper. Chemistry became electricity.' },
  LI_BATTERY:   { id:'LI_BATTERY',   name:'Lithium Battery',  symbol:'Li+CoO₂', sub:'', emoji:'📱', tier:'compound', color:'#44BBFF', shadow:'rgba(68,187,255,0.4)', tc:'white',
                   fact:'Lithium ions shuttle between electrodes. Powers phones, laptops, EVs. Nobel Prize in Chemistry 2019. The technology that untethered humanity.' },
  NEON_SIGN:    { id:'NEON_SIGN',    name:'Neon Sign',        symbol:'Ne+glass', sub:'', emoji:'💗', tier:'compound', color:'#FF3366', shadow:'rgba(255,51,102,0.5)', tc:'white',
                   fact:'Neon gas in glass tube + electricity = red-orange glow. Invented 1910 in Paris. Each noble gas glows a different color. Visual language of nightlife.' },
  LIGHT_BULB:   { id:'LIGHT_BULB',   name:'Light Bulb',       symbol:'W+Ar',    sub:'', emoji:'💡', tier:'compound', color:'#FFEE88', shadow:'rgba(255,238,136,0.4)', tc:'#333',
                   fact:'Tungsten filament in argon gas. Heats to 2,700°C and glows. Edison didn\'t invent it — he perfected it. Argon prevents the filament from burning.' },
  MIRROR:       { id:'MIRROR',       name:'Mirror',           symbol:'Ag+glass', sub:'', emoji:'🪞', tier:'compound', color:'#DDDDEE', shadow:'rgba(221,221,238,0.4)', tc:'#333',
                   fact:'Nanometer-thin silver coating on glass via Tollens\' reaction. Before this, mirrors were polished bronze. Silvering changed vanity forever.' },
  CERAMIC:      { id:'CERAMIC',      name:'Ceramic',          symbol:'Al₂O₃+SiO₂',sub:'',emoji:'🏺',tier:'compound',color:'#CC9966',shadow:'rgba(204,153,102,0.4)',tc:'white',
                   fact:'Aluminum oxide + silicon dioxide, fired at extreme heat. Older than metal — ceramic pottery dates to 29,000 BCE. Beautifully ancient technology.' },
  DIAMOND:      { id:'DIAMOND',      name:'Diamond',          symbol:'C',        sub:'diamond',emoji:'💎',tier:'compound',color:'#BBDDFF',shadow:'rgba(187,221,255,0.5)',tc:'#333',
                   fact:'Pure carbon. Each atom bonded to 4 neighbors in a perfect tetrahedron. Hardest natural material. Formed 150km underground. Also technically flammable.' },
  AMINO_ACID:   { id:'AMINO_ACID',   name:'Amino Acid',       symbol:'NH₂COOH', sub:'', emoji:'🧬', tier:'compound', color:'#FF88AA', shadow:'rgba(255,136,170,0.4)', tc:'white',
                   fact:'Building blocks of protein. 20 types. Your DNA is a recipe book for arranging these. Life runs on amino acid Legos.' },
  PROTEIN:      { id:'PROTEIN',      name:'Protein',          symbol:'polypeptide',sub:'',emoji:'🧬',tier:'compound',color:'#FF5588',shadow:'rgba(255,85,136,0.5)',tc:'white',
                   fact:'Amino acid chains folded into 3D shapes. Enzymes, muscles, antibodies. Your body makes 20,000 kinds. Folding them correctly is biology\'s hardest problem.' },
  DNA:          { id:'DNA',          name:'DNA',              symbol:'double helix',sub:'',emoji:'🧬',tier:'compound',color:'#FF44AA',shadow:'rgba(255,68,170,0.5)',tc:'white',
                   fact:'3 billion base pairs in every cell. If uncoiled, each cell\'s DNA stretches 2 meters. Your whole body\'s DNA would reach the sun and back 600 times.' },
  ATP:          { id:'ATP',          name:'ATP',              symbol:'energy',   sub:'', emoji:'⚡', tier:'compound', color:'#FFAA33', shadow:'rgba(255,170,51,0.4)', tc:'#333',
                   fact:'Energy currency of all living cells. Break one phosphate bond, release energy. Your body recycles its own weight in ATP every single day. Molecular money.' },
  HEMOGLOBIN:   { id:'HEMOGLOBIN',   name:'Hemoglobin',       symbol:'Fe-protein',sub:'',emoji:'🩸',tier:'compound',color:'#CC2222',shadow:'rgba(204,34,34,0.5)',tc:'white',
                   fact:'Iron atom in a protein cage. Grabs oxygen in lungs, releases in tissues. Why blood is red. Every breath relies on iron chemistry in your veins.' },
  CHLOROPHYLL:  { id:'CHLOROPHYLL',  name:'Chlorophyll',      symbol:'Mg-protein',sub:'',emoji:'🌿',tier:'compound',color:'#22AA44',shadow:'rgba(34,170,68,0.5)',tc:'white',
                   fact:'Magnesium in a protein cage. Captures sunlight. Why plants are green — absorbs red and blue, reflects green. Almost identical to hemoglobin but with Mg instead of Fe.' },
  GREENHOUSE:   { id:'GREENHOUSE',   name:'Greenhouse Effect',symbol:'CO₂+CH₄', sub:'', emoji:'🌡️', tier:'compound', color:'#FF9955', shadow:'rgba(255,153,85,0.4)', tc:'white',
                   fact:'CO₂ and methane trap heat in the atmosphere. Without it, Earth = -18°C. With too much... you\'ve seen the news. Balance is everything.' },
  HARD_WATER:   { id:'HARD_WATER',   name:'Hard Water',       symbol:'Ca(HCO₃)₂',sub:'',emoji:'🚿',tier:'compound',color:'#BBCCDD',shadow:'rgba(187,204,221,0.4)',tc:'#333',
                   fact:'Water with dissolved calcium bicarbonate. Leaves limescale on your kettle. Clogs pipes. Ruins soap lather. Rain dissolves limestone, then annoys homeowners.' },
  LIMESTONE_CAVE:{id:'LIMESTONE_CAVE',name:'Limestone Cave',  symbol:'stalactites',sub:'',emoji:'🦇',tier:'compound',color:'#AA9977',shadow:'rgba(170,153,119,0.4)',tc:'white',
                   fact:'Hard water drips, CO₂ escapes, calcium carbonate deposits. One drip at a time, millions of years. Stalactites hold tight (ceiling), stalagmites might reach up (floor).' },
  OZONE_LAYER:  { id:'OZONE_LAYER',  name:'Ozone Layer',      symbol:'O₃ shield',sub:'',emoji:'🛡️',tier:'compound',color:'#44AAFF',shadow:'rgba(68,170,255,0.5)',tc:'white',
                   fact:'15-35km up. Absorbs 97-99% of UV radiation. CFCs punched a hole in it. We banned CFCs. It\'s healing. Rare good news in atmospheric chemistry.' },
  GUNPOWDER:    { id:'GUNPOWDER',    name:'Gunpowder',        symbol:'KNO₃+C+S',sub:'',emoji:'💥',tier:'compound',color:'#555544',shadow:'rgba(85,85,68,0.5)',tc:'white',
                   fact:'Saltpeter + charcoal + sulfur. Invented in 9th century China while searching for immortality. Found the exact opposite. Changed warfare forever.' },
  NUCLEAR_POWER:{ id:'NUCLEAR_POWER',name:'Nuclear Power',    symbol:'fission+H₂O',sub:'',emoji:'⚡',tier:'compound',color:'#44FF88',shadow:'rgba(68,255,136,0.5)',tc:'#002',
                   fact:'Controlled fission boils water to spin turbines. One uranium pellet = 17,000 cubic feet of natural gas. Zero carbon emissions. Complicated feelings.' },
  AQUA_REGIA:   { id:'AQUA_REGIA',   name:'Aqua Regia',       symbol:'HNO₃+HCl',sub:'',emoji:'👑',tier:'compound',color:'#FFAA00',shadow:'rgba(255,170,0,0.5)',tc:'#333', danger:true,
                   fact:'⚠️ DANGER ZONE. Royal water — dissolves gold and platinum. Niels Bohr dissolved Nobel Prize medals in this to hide them from the Nazis. Recovered after the war.' },

  // ── DANGER ZONE ☠️ ──
  Cl2:     { id:'Cl2',     name:'Chlorine Gas',    symbol:'Cl₂',   sub:'gas',  emoji:'☠️', tier:'danger', color:'#88FF44', shadow:'rgba(100,220,50,0.6)', tc:'#002', danger:true,
             fact:'⚠️ DANGER ZONE. Used as a chemical weapon in WWI. Heavier than air so it sinks into trenches. Causes your lungs to fill with fluid. Smells like a swimming pool, but way more fatal. The swimming pool smell IS this gas — just very diluted.' },
  TNT:     { id:'TNT',     name:'TNT',             symbol:'C₇H₅N₃O₆',sub:'💥',emoji:'💣',tier:'danger',color:'#FF8800',shadow:'rgba(255,100,0,0.7)',tc:'white',danger:true,
             fact:'⚠️ DANGER ZONE. Trinitrotoluene. Releases energy stored in those nitrogen-oxygen bonds instantaneously. Invented in 1863. Originally used as a yellow dye. Then someone noticed it explodes. Oops. Still used to measure energy in "tons of TNT".' },
  H2O2:    { id:'H2O2',    name:'Hydrogen Peroxide',symbol:'H₂O₂',sub:'',     emoji:'🫧', tier:'danger', color:'#CCDDFF', shadow:'rgba(180,200,255,0.5)', tc:'#333', danger:true,
             fact:'⚠️ DANGER ZONE. Water\'s unstable cousin. An extra oxygen atom that REALLY wants to leave. 3% solution bleaches your hair. 30% will burn through skin. 90% concentration is used as rocket fuel. Yes. Rocket. Fuel.' },
  ACID:    { id:'ACID',    name:'Sulfuric Acid',   symbol:'H₂SO₄', sub:'',     emoji:'🧪', tier:'danger', color:'#FFEE00', shadow:'rgba(255,238,0,0.6)', tc:'#332', danger:true,
             fact:'⚠️ DANGER ZONE. The most industrially produced chemical on Earth. Dissolves almost everything. Generates so much heat when mixed with water that the water boils. You add acid to water, never water to acid. This is not optional advice.' },
  NITROGLYCERIN:{ id:'NITROGLYCERIN',name:'Nitroglycerin',symbol:'C₃H₅N₃O₉',sub:'',emoji:'💥',tier:'danger',color:'#FF2200',shadow:'rgba(255,34,0,0.7)',tc:'white',danger:true,
             fact:'⚠️ DANGER ZONE. So sensitive it can detonate from a slight vibration, temperature change, or a bad vibe. Alfred Nobel invented dynamite by stabilizing it with sand. Then felt so guilty about explosives he created the Nobel Peace Prize. Both facts are true.' },
  OZONE:   { id:'OZONE',   name:'Ozone',           symbol:'O₃',    sub:'',     emoji:'🌐', tier:'danger', color:'#44BBFF', shadow:'rgba(68,187,255,0.5)', tc:'white', danger:true,
             fact:'Three oxygen atoms. In the upper atmosphere: blocks UV radiation and saves all life on Earth. At ground level: toxic air pollutant that damages your lungs. Same molecule, two completely different jobs. Location is everything.' },
  BLEACH:  { id:'BLEACH',  name:'Bleach',          symbol:'NaClO',  sub:'',     emoji:'🪣', tier:'danger', color:'#EEFFEE', shadow:'rgba(200,240,200,0.4)', tc:'#333', danger:true,
             fact:'⚠️ DANGER ZONE. Great at killing bacteria. NEVER mix with ammonia — makes chloramine gas, a chemical weapon. NEVER mix with vinegar — makes chlorine gas. NEVER mix with hydrogen peroxide. Bleach is the difficult coworker of your cleaning cabinet.' },
  MUSTARD_GAS:{ id:'MUSTARD_GAS',name:'Mustard Gas',symbol:'C₄H₈Cl₂S',sub:'',emoji:'☣️',tier:'danger',color:'#CCAA00',shadow:'rgba(200,170,0,0.7)',tc:'white',danger:true,
             fact:'⚠️ DANGER ZONE. Not actually a gas — an oily liquid. Not actually mustard. Banned by the Geneva Protocol in 1925. Causes massive blistering of skin and lungs. You can make it by combining sulfur and chlorine compounds. Which is why we\'re not telling you the exact recipe.' },
  HCN:     { id:'HCN',     name:'Hydrogen Cyanide', symbol:'HCN',    sub:'',    emoji:'💀', tier:'danger', color:'#CC77FF', shadow:'rgba(200,120,255,0.6)', tc:'white', danger:true,
             fact:'⚠️ DANGER ZONE. Smells like almonds — but only 40% of people can detect it. Blocks cellular respiration. Your cells literally forget how to use oxygen. Used in gold mining and... worse things throughout history.' },
  PH3:     { id:'PH3',     name:'Phosphine',        symbol:'PH₃',   sub:'gas', emoji:'👻', tier:'danger', color:'#77FF99', shadow:'rgba(100,255,150,0.6)', tc:'#002', danger:true,
             fact:'⚠️ DANGER ZONE. Spontaneously ignites in air. The original will-o\'-the-wisp — mysterious lights floating over swamps at night? That was phosphine from decomposing organic matter. Ghosts are just chemistry.' },
  CHLORAMINE:{ id:'CHLORAMINE',name:'Chloramine Gas',symbol:'NH₂Cl', sub:'gas', emoji:'🫁', tier:'danger', color:'#AAFF44', shadow:'rgba(170,255,68,0.6)', tc:'#002', danger:true,
             fact:'⚠️ DANGER ZONE. What happens when you mix bleach and ammonia. Your cleaning products can combine into a chemical weapon in your bathroom. Burns eyes, throat, lungs, and everything else. READ. THE. LABELS.' },
  PHOSGENE:{ id:'PHOSGENE', name:'Phosgene',        symbol:'COCl₂', sub:'gas', emoji:'☣️', tier:'danger', color:'#99DDAA', shadow:'rgba(150,220,170,0.6)', tc:'#002', danger:true,
             fact:'⚠️ DANGER ZONE. Responsible for 85% of chemical weapon deaths in WWI. Smells like freshly cut hay. By the time you smell it, you\'ve already inhaled a lethal dose. Symptoms take 24-48 hours to appear. Truly nightmarish.' },
  NO2:     { id:'NO2',     name:'Nitrogen Dioxide',  symbol:'NO₂',   sub:'gas', emoji:'🟤', tier:'danger', color:'#CC6633', shadow:'rgba(200,100,50,0.6)', tc:'white', danger:true,
             fact:'⚠️ DANGER ZONE. The brown gas in smog. Reddish-brown, acrid, corrosive. Damages lung tissue at low concentrations. Major component of acid rain. Every car exhaust contains this. You breathe it daily in cities.' },
  THERMITE:{ id:'THERMITE', name:'Thermite',         symbol:'Fe₂O₃+Al',sub:'',  emoji:'🌋', tier:'danger', color:'#FF6600', shadow:'rgba(255,100,0,0.7)', tc:'white', danger:true,
             fact:'⚠️ DANGER ZONE. Iron oxide + aluminum powder. Once ignited, burns at 2,500°C — hot enough to melt through steel beams. Used to weld railroad tracks. Cannot be extinguished with water. Water makes it WORSE. Respect thermite.' },
  // ── New Danger ──
  F2:      { id:'F2',      name:'Fluorine Gas',     symbol:'F₂',    sub:'gas', emoji:'☠️', tier:'danger', color:'#44FF88', shadow:'rgba(68,255,136,0.6)', tc:'#002', danger:true,
             fact:'⚠️ DANGER ZONE. The most reactive substance known to science. Reacts with glass, water, sand, concrete, and even some noble gases. Chemists call working with it exciting. They mean terrifying.' },
  Br2:     { id:'Br2',     name:'Liquid Bromine',   symbol:'Br₂',   sub:'',    emoji:'☠️', tier:'danger', color:'#882211', shadow:'rgba(136,34,17,0.6)', tc:'white', danger:true,
             fact:'⚠️ DANGER ZONE. Dense, fuming, dark red-brown liquid. Named from Greek bromos — stench. The smell is beyond words. You will remember it forever if you encounter it once.' },
  WHITE_P: { id:'WHITE_P', name:'White Phosphorus',  symbol:'P₄',    sub:'',    emoji:'👻', tier:'danger', color:'#EEFF44', shadow:'rgba(238,255,68,0.6)', tc:'#002', danger:true,
             fact:'⚠️ DANGER ZONE. Spontaneously ignites in air. Glows with a ghostly green light in the dark. Burns underwater. Burns through skin. Used in incendiary weapons. Burns.' },
  N2O:     { id:'N2O',     name:'Laughing Gas',      symbol:'N₂O',   sub:'gas', emoji:'😂', tier:'danger', color:'#88DDFF', shadow:'rgba(136,221,255,0.5)', tc:'#002', danger:true,
             fact:'⚠️ DANGER ZONE. Nitrous oxide. Legitimate dental anesthetic. Also an asphyxiant. Also a greenhouse gas 300x worse than CO₂. The fun kind of danger. Still danger.' },
  BENZENE: { id:'BENZENE', name:'Benzene',           symbol:'C₆H₆',  sub:'',    emoji:'💀', tier:'danger', color:'#FF8844', shadow:'rgba(255,136,68,0.6)', tc:'white', danger:true,
             fact:'⚠️ DANGER ZONE. Six carbons in a perfect ring. Smells sweet. Causes leukemia. Was used in aftershave in the early 1900s. Chemistry\'s favorite molecule is also a carcinogen.' },
  KCN:     { id:'KCN',     name:'Potassium Cyanide', symbol:'KCN',   sub:'',    emoji:'☠️', tier:'danger', color:'#CC77FF', shadow:'rgba(200,120,255,0.6)', tc:'white', danger:true,
             fact:'⚠️ DANGER ZONE. Smells like almonds but only 40% of people can detect it. Blocks cellular respiration within minutes. Used in gold mining. History\'s most notorious poison.' },
  MERCURY_VAPOR:{id:'MERCURY_VAPOR',name:'Mercury Vapor',symbol:'Hg(g)',sub:'',  emoji:'👻', tier:'danger', color:'#CCCCEE', shadow:'rgba(200,200,238,0.5)', tc:'#333', danger:true,
             fact:'⚠️ DANGER ZONE. Invisible. Odorless. Cumulative neurotoxin. Liquid mercury evaporates at room temperature. Mad hatter disease came from mercury in felt-making. The trembling was not excitement.' },
  HgCl2_D: { id:'HgCl2_D', name:'Mercury Chloride', symbol:'HgCl₂', sub:'',    emoji:'☠️', tier:'danger', color:'#AABBCC', shadow:'rgba(170,187,204,0.5)', tc:'#333', danger:true,
             fact:'⚠️ DANGER ZONE. Corrosive sublimate. Historical poison of choice for centuries. Dissolves in water, nearly tasteless. Banned from basically everything now.' },
  LEAD_PAINT:{id:'LEAD_PAINT',name:'Lead Paint',     symbol:'PbCO₃', sub:'',    emoji:'🎨', tier:'danger', color:'#DDDDAA', shadow:'rgba(220,220,170,0.5)', tc:'#333', danger:true,
             fact:'⚠️ DANGER ZONE. White lead — beautiful, durable, catastrophically poisonous. Used for millennia. Banned in the US in 1978. Still in millions of older homes. Kids eat the sweet-tasting chips.' },
  UF6:     { id:'UF6',     name:'Uranium Hexafluoride',symbol:'UF₆', sub:'',    emoji:'☢️', tier:'danger', color:'#55FF88', shadow:'rgba(85,255,136,0.6)', tc:'#002', danger:true,
             fact:'⚠️ DANGER ZONE. Used in uranium enrichment for nuclear weapons and reactors. Radioactive AND corrosive. Reacts violently with water. The most dangerous compound most people have never heard of.' },
  NUCLEAR_FISSION:{id:'NUCLEAR_FISSION',name:'Nuclear Fission',symbol:'U-235',sub:'',emoji:'☢️',tier:'danger',color:'#FF4400',shadow:'rgba(255,68,0,0.7)',tc:'white',danger:true,
             fact:'⚠️ DANGER ZONE. Split one uranium atom, it releases neutrons that split more. Chain reaction. Little Boy used 64 kg of U-235. The energy of 15,000 tons of TNT in a suitcase-sized core.' },
  NAPALM:  { id:'NAPALM',  name:'Napalm',            symbol:'gel fuel',sub:'',  emoji:'🔥', tier:'danger', color:'#FF6600', shadow:'rgba(255,102,0,0.7)', tc:'white', danger:true,
             fact:'⚠️ DANGER ZONE. Gasoline gelled with a thickening agent. Sticks to surfaces. Burns at 800-1200°C. Cannot be removed or extinguished. Developed at Harvard in 1942. The ivory tower has a dark basement.' },
};

const REACTIONS_RAW = [
  // ── Atoms → Diatomic Molecules ──
  [['H','H'],            'H2'],
  [['O','O'],            'O2'],
  [['N','N'],            'N2'],
  [['Cl','Cl'],          'Cl2'],     // ☠️

  // ── Water ──
  [['H2','O'],           'H2O'],
  [['H2','O2'],          'H2O'],     // simplified combustion

  // ── Carbon oxides ──
  [['C','O'],            'CO'],      // limited O → CO
  [['C','O2'],           'CO2'],     // excess O → CO2
  [['CO','O'],           'CO2'],
  [['CO','O2'],          'CO2'],

  // ── Salt ──
  [['Na','Cl'],          'NaCl'],

  // ── Ammonia ──
  [['N','H'],            'NH3'],     // simplified
  [['N2','H2'],          'NH3'],     // Haber process
  [['N','H2'],           'NH3'],

  // ── Methane ──
  [['C','H2'],           'CH4'],
  [['C','H'],            'CH4'],     // simplified
  [['CH4','O2'],         'CO2'],     // combustion

  // ── Sulfur compounds ──
  [['H','S'],            'H2S'],
  [['H2','S'],           'H2S'],
  [['S','O'],            'SO2'],
  [['S','O2'],           'SO2'],

  // ── Halogen acids ──
  [['H','Cl'],           'HCl'],

  // ── Nitric oxide ──
  [['N','O'],            'NO'],
  [['NO','O'],           'NO2'],     // ☠️
  [['NO','O2'],          'NO2'],     // ☠️

  // ── Iron ──
  [['Fe','O'],           'FeO'],
  [['Fe','O2'],          'FeO'],
  [['Fe','C'],           'STEEL'],
  [['Fe','HCl'],         'FeCl2'],

  // ── Calcium ──
  [['Ca','P'],           'BONES'],
  [['Ca','O'],           'CaO'],
  [['CaO','CO2'],        'CaCO3'],
  [['Ca','CO2'],         'CaCO3'],
  [['CaO','H2O'],        'CEMENT'],
  [['Ca','HCl'],         'CaCl2'],
  [['Ca','Cl'],          'CaCl2'],

  // ── Magnesium ──
  [['Mg','O'],           'MgO'],
  [['Mg','O2'],          'MgO'],

  // ── Potassium / Sodium hydroxides ──
  [['K','H2O'],          'KOH'],
  [['Na','H2O'],         'NaOH'],

  // ── Silicon ──
  [['Si','O2'],          'SiO2'],
  [['Si','O'],           'SiO2'],

  // ── Compounds ──
  [['NaCl','H2O'],       'SALT_WATER'],
  [['H2O','CO2'],        'CARBONIC_ACID'],
  [['SALT_WATER','H2O'], 'OCEAN'],
  [['SALT_WATER','NaCl'],'OCEAN'],
  [['N2','O2'],          'ATMOSPHERE'],
  [['CARBONIC_ACID','O2'],'PHOTOSYNTHESIS'],  // conceptual: CO₂+H₂O+light→sugar+O₂
  [['PHOTOSYNTHESIS','ATMOSPHERE'],'LIFE'],
  [['SO2','H2O'],        'ACID_RAIN'],
  [['H2O','HCl'],        'STOMACH_ACID'],
  [['NH3','CO2'],         'FERTILIZER'],
  [['NaOH','CO2'],        'BAKING_SODA'],
  [['NaOH','HCl'],        'NEUTRALIZATION'],
  [['SiO2','NaOH'],       'GLASS'],
  [['SiO2','Na'],         'GLASS'],
  [['NO2','SO2'],          'SMOG'],
  [['NO','SO2'],           'SMOG'],

  // ── Danger Zone ☠️ ──
  [['H2O','O'],          'H2O2'],     // water + atomic O → peroxide
  [['SO2','H2O2'],       'ACID'],     // SO₂ oxidation → H₂SO₄
  [['ACID_RAIN','O'],    'ACID'],     // H₂SO₃ + O → H₂SO₄
  [['ACID_RAIN','O2'],   'ACID'],
  [['NaCl','O'],         'BLEACH'],
  [['NaOH','Cl'],        'BLEACH'],
  [['NaOH','Cl2'],       'BLEACH'],
  [['O2','O'],           'OZONE'],
  [['S','Cl'],           'MUSTARD_GAS'],
  [['H2S','Cl2'],        'MUSTARD_GAS'],
  [['CH4','NO2'],        'TNT'],      // hydrocarbon + nitro group → nitro explosive
  [['NH3','O2'],         'NITROGLYCERIN'],  // simplified
  [['NH3','C'],          'HCN'],      // Andrussow process simplified
  [['C','N'],            'HCN'],      // carbon + nitrogen → cyanide
  [['P','H2'],           'PH3'],
  [['P','H'],            'PH3'],
  [['NH3','Cl2'],        'CHLORAMINE'],
  [['BLEACH','NH3'],     'CHLORAMINE'],
  [['CO','Cl2'],         'PHOSGENE'],
  [['FeO','Al'],         'THERMITE'],
  [['FeO','Mg'],         'THERMITE'],

  // ── New: Halogen acids ──
  [['H','F'],            'HF'],
  [['H','Br'],           'HBr'],
  [['H','I'],            'HI'],
  // ── New: Sodium/potassium halides ──
  [['Na','F'],           'NaF'],
  [['Na','Br'],          'NaBr'],
  [['Na','I'],           'NaI'],
  [['K','Cl'],           'KCl'],
  // ── New: Metal oxides ──
  [['Cu','O'],           'CuO'],
  [['Zn','O'],           'ZnO'],
  [['Ti','O2'],          'TiO2'],
  [['Ti','O'],           'TiO2'],
  [['Cr','O'],           'Cr2O3'],
  [['Cr','O2'],          'Cr2O3'],
  [['Mn','O2'],          'MnO2'],
  [['Mn','O'],           'MnO2'],
  [['Al','O2'],          'Al2O3'],
  [['Al','O'],           'Al2O3'],
  [['Ba','O'],           'BaO'],
  [['W','O2'],           'WO3'],
  [['Hg','O'],           'HgO'],
  [['Pb','O'],           'PbO'],
  [['U','O2'],           'UO2'],
  [['Ni','O'],           'NiO'],
  [['Co','O'],           'CoO'],
  [['Sn','O2'],          'SnO2'],
  // ── New: Sulfides ──
  [['Fe','S'],           'FeS'],
  [['FeS','S'],          'FeS2'],
  [['Cu','S'],           'CuS'],
  [['Zn','S'],           'ZnS'],
  [['Pb','S'],           'PbS'],
  // ── New: Hydroxides ──
  [['MgO','H2O'],        'Mg_OH_2'],
  [['Al2O3','H2O'],      'Al_OH_3'],
  [['BaO','H2O'],        'Ba_OH_2'],
  [['Li','H2O'],         'LiOH'],
  // ── New: Silver ──
  [['Ag','Cl'],          'AgCl'],
  [['Ag','HNO3'],        'AgNO3'],
  // ── New: Copper compounds ──
  [['Cu','HCl'],         'CuCl2'],
  [['Cu','Cl2'],         'CuCl2'],
  [['Cu','ACID'],        'CuSO4'],
  [['CuO','CO2'],        'CuCO3'],
  // ── New: Lead/Mercury ──
  [['Pb','Cl'],          'PbCl2'],
  [['Hg','Cl2'],         'HgCl2_D'],
  // ── New: Acids ──
  [['NO2','H2O'],        'HNO3'],
  [['P','H2O'],          'H3PO4'],
  // ── New: Carbonates ──
  [['MgO','CO2'],        'MgCO3'],
  [['BaO','CO2'],        'BaCO3'],
  [['BAKING_SODA','NaOH'],'Na2CO3'],
  // ── New: Barium sulfate ──
  [['Ba','ACID'],        'BaSO4'],
  // ── New: Saltpeter + Gunpowder ──
  [['K','HNO3'],         'KNO3'],
  [['KNO3','S'],         'GUNPOWDER'],
  // ── New: Diatomic/allotropes ──
  [['F','F'],            'F2'],
  [['Br','Br'],          'Br2'],
  [['I','I'],            'I2'],
  [['C','C'],            'DIAMOND'],
  [['P','P'],            'WHITE_P'],
  // ── New: Alloys + materials ──
  [['Cu','Zn'],          'BRASS'],
  [['Cu','Sn'],          'BRONZE'],
  [['STEEL','Cr'],       'STAINLESS'],
  [['Sn','Pb'],          'SOLDER'],
  [['Zn','CuSO4'],       'BATTERY'],
  [['Li','CoO'],         'LI_BATTERY'],
  [['Ne','GLASS'],       'NEON_SIGN'],
  [['W','Ar'],           'LIGHT_BULB'],
  [['Ag','GLASS'],       'MIRROR'],
  [['Al2O3','SiO2'],     'CERAMIC'],
  // ── New: Organic chemistry ──
  [['CO','H2'],          'METHANOL'],
  [['METHANOL','CH4'],   'ETHANOL'],
  [['CH4','CH4'],        'ETHYLENE'],
  [['CaO','C'],          'ACETYLENE'],
  [['ETHANOL','O2'],     'ACETIC_ACID'],
  [['METHANOL','O'],     'FORMALDEHYDE'],
  [['PHOTOSYNTHESIS','H2O'],'GLUCOSE'],
  [['NaOH','ACETIC_ACID'],'SOAP'],
  [['ETHYLENE','CH4'],   'PROPANE'],
  [['PROPANE','CH4'],    'BUTANE'],
  [['ACETYLENE','ACETYLENE'],'BENZENE'],
  // ── New: Biochemistry ──
  [['NH3','ACETIC_ACID'], 'AMINO_ACID'],
  [['AMINO_ACID','AMINO_ACID'],'PROTEIN'],
  [['GLUCOSE','H3PO4'],  'DNA'],
  [['DNA','PROTEIN'],    'ATP'],
  [['Fe','PROTEIN'],     'HEMOGLOBIN'],
  [['Mg','PROTEIN'],     'CHLOROPHYLL'],
  // ── New: Environmental ──
  [['CO2','CH4'],        'GREENHOUSE'],
  [['CaCO3','CARBONIC_ACID'],'HARD_WATER'],
  [['HARD_WATER','CaCO3'],'LIMESTONE_CAVE'],
  [['OZONE','ATMOSPHERE'],'OZONE_LAYER'],
  // ── New: Nuclear ──
  [['UO2','H2O'],        'NUCLEAR_POWER'],
  [['U','F2'],           'UF6'],
  [['UF6','UO2'],        'NUCLEAR_FISSION'],
  // ── New: Danger reactions ──
  [['N','NO'],           'N2O'],
  [['KOH','HCN'],        'KCN'],
  [['HgO','C'],          'MERCURY_VAPOR'],
  [['Pb','CO2'],         'LEAD_PAINT'],
  [['BENZENE','PROPANE'],'NAPALM'],
  [['HNO3','HCl'],       'AQUA_REGIA'],
];

function makeKey(a,b) { return [a,b].sort().join('+'); }
const REACTIONS = {};
REACTIONS_RAW.forEach(([pair,result]) => {
  REACTIONS[makeKey(pair[0],pair[1])] = result;
});

const GIZMO_LINES = {
  idle: [
    "Combine two elements to get started!",
    "Try H + H first... go on.",
    "Science waits for no one. Mostly.",
    "I have a PhD you know. Several.",
    "Those atoms won't combine themselves.",
    "What are you waiting for? Discover something!",
    "I once combined sodium and chlorine at a party. I was very popular.",
    "Every atom in your body was forged in a dying star. No pressure.",
  ],
  normal: {
    H2:   "Hydrogen gas! Incredibly flammable. The Hindenburg learned this the hard way.",
    O2:   "Oxygen gas! The stuff keeping you alive. Don't take it for granted.",
    H2O:  "WATER! Two explosive gases walked into a bar and became... drinkable! I love chemistry!",
    N2:   "Nitrogen gas. 78% of every breath and it does absolutely nothing. Freeloading molecule.",
    NaCl: "SALT! An exploding metal + a poison gas = the thing you put on fries. Chefs kiss. 🤌",
    CO2:  "Carbon dioxide! You're exhaling this right now. Plants consider that breakfast.",
    NH3:  "Ammonia! Smells like a thousand cats. Feeds half the world. Complicated legacy.",
    H2S:  "...that's the fart molecule. I'm not judging you. I'm judging it. A little.",
    SO2:  "Sulfur dioxide. What volcanoes breathe out. They're not great neighbors.",
    HCl:  "Hydrochloric acid! Your stomach makes this right now. You're a walking chemistry lab.",
    FeO:  "Rust! You turned iron into sadness. Slowly. Inevitably. Poetically.",
    CH4:  "Methane! Swamp gas, cow emissions, natural gas. Simple but powerful. Like me.",
    MgO:  "Magnesium oxide! That blinding white flash in fireworks? You just made it. Beautiful.",
    KOH:  "Potassium hydroxide! Caustic potash. Makes soap and batteries. Busy molecule.",
    NaOH: "Sodium hydroxide — LYE! Dissolves almost anything organic. Including... nope, not finishing that thought.",
    FeCl2:"Iron chloride! The iron dissolved in acid. Green crystals of sacrifice. Noble.",
    CaCl2:"Calcium chloride! The stuff that melts ice on roads. Winter's nemesis.",
    NO:   "Nitric oxide! Your blood vessels use this to relax. Nobel Prize winner, 1998. Fancy.",
    SiO2: "Silicon dioxide — that's SAND! Also glass. Also quartz. Same molecule, different vibes.",
    STEEL: "STEEL! Iron + a pinch of carbon = 1000x stronger. The power of teamwork!",
    BONES: "BONE! You're literally made of calcium phosphate rocks. You are a rock person.",
    SALT_WATER: "Salt water! 3.5% salt. Undrinkable. Full of sharks. Two reasons to avoid it.",
    CARBONIC_ACID: "Carbonic acid — this is what makes soda fizzy! You're a soda scientist now.",
    ACID_RAIN: "Acid rain. That's what happens when volcanoes and factories misbehave. Disappointing.",
    STOMACH_ACID: "Stomach acid! You have a vat of pH 1.5 acid inside you RIGHT NOW. Sleep well!",
    ATMOSPHERE: "THE ATMOSPHERE! The only thing between you and the void of space! Good job making it!",
    PHOTOSYNTHESIS: "PHOTOSYNTHESIS! The most important reaction on Earth! I'm not crying. YOU'RE crying!",
    OCEAN: "THE OCEAN!! You made the whole ocean!! I need a moment. This is genuinely beautiful.",
    LIFE: "...LIFE. You made LIFE. I've been waiting my whole career for this. *openly weeping*",
    CaO:  "Quicklime! Add water and it gets white-hot. Romans loved it. Dangerous fun.",
    CaCO3:"Limestone! Seashells and marble — same stuff. Billions of years of dead sea creatures.",
    FERTILIZER: "FERTILIZER! The Haber process feeds half the planet. Nobel Prize AND war crimes. Complicated.",
    CEMENT: "CEMENT! Romans built with this 2000 years ago. Their stuff still stands. Ours... less so.",
    BAKING_SODA: "Baking soda! Makes cakes rise, calms stomachs, fights fires. Most useful powder in the kitchen.",
    NEUTRALIZATION: "NEUTRALIZATION! Acid + base = salt water. Chemistry's greatest punchline. Every time.",
    GLASS: "GLASS! Melted sand frozen in chaos. Transparent because photons just fly right through. Wild.",
    SMOG: "Smog. The brown haze of progress. London 1952 — 12,000 people. Clean air matters.",
    // ── New molecule lines ──
    LiOH: "Lithium hydroxide! Astronauts use this to breathe. You just made space chemistry.",
    HF: "Hydrofluoric acid. Technically 'weak.' Will still dissolve your bones. Words lie sometimes.",
    HBr: "Hydrobromic acid! The middle child of halogen acids. Capable but overlooked.",
    HI: "Hydroiodic acid — strongest of the hydrogen halides. Quiet powerhouse.",
    NaF: "Sodium fluoride! The thing protecting your teeth right now. Probably. Hopefully.",
    NaBr: "Sodium bromide. Victorian sedative. The word 'bromide' literally means 'boring' because of this.",
    NaI: "Sodium iodide! Glows when radiation hits it. A literal radiation detector. Useful at parties. Nuclear parties.",
    KCl: "Potassium chloride. Salt substitute AND lethal injection drug. Same molecule. Very different vibes.",
    CuO: "Copper oxide! This is why the Statue of Liberty is green. Patience + oxygen = art.",
    ZnO: "Zinc oxide! That white stuff on lifeguards' noses. UV shield since before SPF ratings existed.",
    TiO2: "Titanium dioxide — the whitest white. In every white paint on Earth. You've been looking at it your whole life.",
    Cr2O3: "Chromium oxide! That military green? This. Ancient Egyptian green? Also this. 4,000 years of green.",
    MnO2: "Manganese dioxide! Inside every battery AND in cave paintings from 30,000 years ago. Ancient tech, meet modern tech.",
    Al2O3: "CORUNDUM! Sapphires are this. Rubies are this. Same mineral, different impurities. Mind. Blown.",
    BaO: "Barium oxide. Absorbs CO₂ and moisture like it's getting paid for it. Hygroscopic overachiever.",
    WO3: "Tungsten trioxide! Smart windows use this — apply voltage and it tints. The future is tungsten.",
    HgO: "Mercury oxide! Priestley heated this in a shed and discovered OXYGEN. A shed. In 1774. Science.",
    PbO: "Lead oxide. Renaissance painters loved it. Their trembling hands told a different story.",
    UO2: "Uranium dioxide. Nuclear fuel pellets. One pellet = one year of electricity for a home. Tiny but mighty.",
    FeS: "Iron sulfide! Hit it with steel and it sparks. That's how fire starters work. Ancient chemistry.",
    FeS2: "PYRITE! Fool's gold! It fooled prospectors for centuries. Shiny, golden, and worthless. Chemistry trolling humanity.",
    CuS: "Covellite — copper sulfide with an iridescent purple sheen. Nature showing off again.",
    ZnS: "Zinc sulfide! Those glow-in-the-dark stars on your ceiling? This molecule. Childhood in crystal form.",
    PbS: "Galena! The original semiconductor. Crystal radios in the 1900s — wireless communication started HERE.",
    H3PO4: "Phosphoric acid. In every can of Coke. pH 2.8. Your teeth and I have concerns.",
    AgCl: "Silver chloride — darkens in light. This is literally how photography works. Frozen photons.",
    AgNO3: "Silver nitrate! Makes invisible ink. Also cauterizes wounds. Also stains skin BLACK. Wear gloves.",
    CuCl2: "Copper chloride — turquoise solution, green flames in fireworks. Chemistry's favorite color.",
    CuSO4: "Copper sulfate! Those brilliant blue crystals protecting vineyards since 1885. Beautiful AND useful.",
    PbCl2: "Lead chloride. White crystals. Was in paint for centuries. We... we didn't know. Now we know.",
    NiO: "Nickel oxide. Green ceramics since forever. Also in rechargeable batteries. Old and new.",
    CoO: "Cobalt oxide — THAT blue. The blue in ancient Egyptian glass. 4,600 years of irresistible blue.",
    SnO2: "Tin dioxide. Your touchscreen has this on it right now. Bronze Age ore meets smartphone age.",
    I2: "Iodine crystals! Purple vapor when heated. Used as antiseptic. Stains EVERYTHING. Beautiful nuisance.",
    // ── New compound lines ──
    Mg_OH_2: "Milk of magnesia! Your stomach's best friend at 2 AM after questionable life choices.",
    Al_OH_3: "Aluminum hydroxide — antacid AND water purifier. The responsible molecule in your cabinet.",
    Ba_OH_2: "Barium hydroxide! Gets COLD when dissolved. Endothermic. Chemistry doing the unexpected.",
    MgCO3: "Climber's chalk! Absorbs moisture, prevents sweaty palms. Magnesite keeping you on the wall.",
    CuCO3: "VERDIGRIS! The green on the Statue of Liberty, old church roofs. Copper + time = iconic teal.",
    BaCO3: "Barium carbonate. Rat poison. Also in ceramics. Versatile in a concerning way.",
    BaSO4: "Barium meal! You SWALLOW this for X-rays. Opaque to radiation. The only barium you can safely eat.",
    Na2CO3: "Soda ash! Ancient Egyptians used this for mummies. Now it makes glass. Career change.",
    KNO3: "SALTPETER! Gunpowder ingredient AND fertilizer AND food preservative. One molecule, three jobs.",
    METHANOL: "Methanol — wood alcohol. Looks like vodka. Causes blindness. The evil twin. DO NOT DRINK.",
    ETHANOL: "ETHANOL! The alcohol. 9,000 years of brewing. Humanity domesticated fungus. We're resourceful.",
    ETHYLENE: "Ethylene! Why one bad apple spoils the bunch. Also where all plastic comes from. Tiny but world-changing.",
    ACETYLENE: "Acetylene! Burns at 3,300°C. Cuts steel with oxy-acetylene torches. Miners used this in their lamps.",
    ACETIC_ACID: "Vinegar! Wine gone bad, repurposed as humanity's oldest condiment. Lemons into lemonade. Literally.",
    FORMALDEHYDE: "Formaldehyde. That smell in biology class. Preserves specimens. Also your body makes tiny amounts. Naturally.",
    GLUCOSE: "GLUCOSE! Blood sugar! The fuel of ALL cellular life! Every carb becomes this! THE molecule of energy!",
    SOAP: "SOAP! Fat + lye = the molecule that grabs grease with one end and water with the other. Elegant chemistry.",
    PROPANE: "Propane! BBQ fuel. Three carbons. Clean-burning. I tell you hwat.",
    BUTANE: "Butane! That sloshing in your lighter. Four carbons of portable fire. Pocketable chemistry.",
    BRONZE: "BRONZE! Cu + Sn = the alloy that ended the Stone Age. 3300 BCE. Civilization started here.",
    BRASS: "Brass! Trumpets, doorknobs, bullet casings. Also antimicrobial — bacteria die on it. Self-cleaning metal.",
    STAINLESS: "STAINLESS STEEL! The chromium layer HEALS ITSELF when scratched. Self-repairing metal. 1913 accident.",
    SOLDER: "Solder! Every circuit board connection is this — a tiny metallurgical joint holding your tech together.",
    BATTERY: "THE VOLTAIC CELL! Volta, 1800! Chemistry became electricity! We're standing on a revolution!",
    LI_BATTERY: "LITHIUM BATTERY! Nobel Prize 2019! Untethered humanity from wall sockets! Phones exist because of this!",
    NEON_SIGN: "NEON SIGN! Gas + glass + electricity = the visual language of nightlife! Paris, 1910! Magnifique!",
    LIGHT_BULB: "THE LIGHT BULB! Tungsten in argon! 2,700°C of glow! Edison didn't invent it but he perfected it!",
    MIRROR: "A MIRROR! Silver on glass! Tollens' reaction! Before this, mirrors were polished bronze! Vanity, upgraded!",
    CERAMIC: "Ceramic! Older than metal — 29,000 BCE! Fire + clay = civilization's first manufactured material!",
    DIAMOND: "DIAMOND! Pure carbon under insane pressure! Hardest natural material! Also technically... flammable. Don't test that.",
    AMINO_ACID: "AMINO ACID! Protein building blocks! 20 types! Your DNA is a recipe book for these! Molecular Legos!",
    PROTEIN: "PROTEIN! Folded amino acid chains! Your body makes 20,000 kinds! Biology's origami!",
    DNA: "DNA!! THE DOUBLE HELIX!! 3 billion base pairs! The instruction manual of LIFE! I'm getting emotional!",
    ATP: "ATP! Energy currency of every living cell! Your body recycles its weight in ATP DAILY! Molecular money!",
    HEMOGLOBIN: "HEMOGLOBIN! Iron in a protein cage! Why blood is RED! Every breath depends on this iron chemistry!",
    CHLOROPHYLL: "CHLOROPHYLL! Magnesium in a protein cage! Why plants are GREEN! Almost identical to hemoglobin! BEAUTIFUL!",
    GREENHOUSE: "The greenhouse effect. Without it, Earth = frozen. Too much = disaster. Balance. We're not great at balance.",
    HARD_WATER: "Hard water! That limescale on your kettle. Rain dissolves limestone, then ruins your plumbing.",
    LIMESTONE_CAVE: "A LIMESTONE CAVE! Millions of years of dripping water! Stalactites! Stalagmites! Geological patience!",
    OZONE_LAYER: "THE OZONE LAYER! Shields 97-99% of UV! CFCs punched a hole! We banned them! It's healing! RARE GOOD NEWS!",
    GUNPOWDER: "GUNPOWDER! Invented searching for immortality! Found the opposite! China, 9th century! History is ironic!",
    NUCLEAR_POWER: "NUCLEAR POWER! Boiling water with atoms! Zero carbon! One pellet = a year of electricity! ...complicated.",
    AQUA_REGIA: "⚠️ AQUA REGIA! Dissolves GOLD! Bohr hid Nobel medals in it from the Nazis! Chemistry as resistance!",
  },
  danger: {
    CO:          "⚠️ Carbon monoxide... colorless... odorless... I'm opening EVERY window.",
    Cl2:         "☠️ Chlorine gas! Step back. No, further. FURTHER. Keep going.",
    H2O2:        "Hydrogen peroxide! 3% bleaches hair. 90% is ROCKET FUEL. Put. It. DOWN.",
    H2S:         "Hydrogen sulfide. Rotten eggs + instant death at high concentrations. Charming.",
    ACID:        "SULFURIC ACID! Do NOT add water to it. The water will BOIL and splash acid everywhere. I have seen things.",
    OZONE:       "Ozone! Saves all life from UV at 30km up. At ground level? Destroys your lungs. Location matters.",
    BLEACH:      "Bleach. Do NOT mix with ammonia. Do NOT mix with vinegar. Do NOT mix with ANYTHING. It's the difficult coworker of chemicals.",
    TNT:         "...you made TNT. I'm going to stand over here now. Way over HERE. Further. FURTHER.",
    NITROGLYCERIN: "NITROGLYCERIN?! Detonates from a SLIGHT VIBRATION! I'm typing very carefully right now!",
    MUSTARD_GAS: "MUSTARD GAS?! EVERYBODY OUT! THIS IS NOT A DRILL! I QUIT! I UNQUIT BECAUSE SCIENCE BUT STILL!",
    HCN:         "HYDROGEN CYANIDE! Smells like almonds! Stops your cells from breathing! Fun facts NOBODY WANTED!",
    PH3:         "PHOSPHINE! The will-o'-the-wisp molecule! Spontaneously ignites! Ghosts were chemistry ALL ALONG!",
    CHLORAMINE:  "CHLORAMINE GAS! This is literally what happens when you mix bleach and ammonia! READ CLEANING LABELS!",
    PHOSGENE:    "PHOSGENE?! 85% of WWI gas deaths! Smells like fresh hay! I am DEEPLY uncomfortable right now!",
    NO2:         "Nitrogen dioxide! Brown, toxic, in every car exhaust! The invisible price of driving!",
    THERMITE:    "THERMITE! 2,500°C! MELTS STEEL! WATER MAKES IT WORSE! I need to sit down. On a different continent.",
    HNO3:        "NITRIC ACID! Turns skin YELLOW on contact! Makes fertilizer AND explosives! DUAL-USE CHEMISTRY!",
    F2:          "FLUORINE GAS?! Most reactive substance KNOWN! It reacts with GLASS! WITH SAND! WITH EVERYTHING! WHY DID YOU MAKE THIS?!",
    Br2:         "LIQUID BROMINE! Dense, fuming, red-brown, and the SMELL — oh the smell! Named 'stench' in Greek! ACCURATE!",
    WHITE_P:     "WHITE PHOSPHORUS?! SPONTANEOUSLY IGNITES! GLOWS GREEN IN THE DARK! BURNS UNDERWATER! BURNS THROUGH— I'm leaving!",
    N2O:         "Laughing gas! Hehe... hehe... wait it's also an asphyxiant and 300x worse greenhouse gas. Less funny now.",
    BENZENE:     "BENZENE! Perfect hexagonal ring! Smells sweet! Causes leukemia! Was in AFTERSHAVE! THE EARLY 1900s WERE WILD!",
    KCN:         "POTASSIUM CYANIDE! The most notorious poison in HISTORY! Blocks cellular respiration! I need to go wash my hands. Both of them.",
    MERCURY_VAPOR:"MERCURY VAPOR! Invisible! Odorless! Accumulates in your BRAIN! Mad hatters weren't mad for fun! I'm holding my breath!",
    HgCl2_D:     "MERCURY CHLORIDE! Corrosive sublimate! Historical poison of CHOICE for CENTURIES! Tasteless in water! HORRIFYING!",
    LEAD_PAINT:  "LEAD PAINT! Beautiful! Durable! CATASTROPHICALLY POISONOUS! Used for MILLENNIA! Kids eat the SWEET-TASTING chips! BAN IT!",
    UF6:         "URANIUM HEXAFLUORIDE?! Radioactive AND corrosive?! Used in NUCLEAR ENRICHMENT?! This is above my pay grade! WAY above!",
    NUCLEAR_FISSION:"NUCLEAR FISSION?! YOU SPLIT THE ATOM?! 15,000 TONS OF TNT FROM 64 KILOGRAMS?! I am PROFOUNDLY uncomfortable right now!!",
    NAPALM:      "NAPALM?! STICKS TO EVERYTHING! BURNS AT 1,200°C! DEVELOPED AT HARVARD?! THE IVORY TOWER HAS A DARK BASEMENT!!",
    AQUA_REGIA:  "AQUA REGIA! Dissolves GOLD! Bohr hid Nobel medals in this from the Nazis! Chemistry as RESISTANCE! ...still terrifying though.",
    default:     "☠️ That's... that's very dangerous. I need you to know I had nothing to do with this. My lawyer agrees.",
  },
  no_reaction: [
    "Hmm. Nothing happened. Try something else.",
    "Nope. Chemistry says no.",
    "Not everything reacts. Yet.",
    "Interesting attempt. Wrong, but interesting.",
    "I've seen worse ideas. Not many, but some.",
    "My notes say... no. Definitely no.",
    "That's not a thing. Trust me. I checked.",
    "If that worked, I'd have a Nobel Prize.",
  ],
  unlock: [
    "A new element! The periodic table grows!",
    "Look what you unlocked! Use it wisely. Or unwisely. I'm not your supervisor.",
    "New atom! The possibilities multiply! Dangerously!",
    "Fresh element! Your lab just got more interesting!",
  ]
};
